### ISSUE TITLE
Missing DPs for "old" light added with "new" version of localtuya

### ISSUE THREAD

**Issue by clemente3905** [rospogrigio/localtuya#1033]
## The problem

I have over 30 tuya lights (all the same) all integrated in Home assistant with older version of localtuya and they all worked flawlessly.
Today I bought a new light, SAME MODEL of another already integrated and have to follow the "new" setup to integrate.
The integrated light is missing color and scene (which are DP 24 and 25) but is perfectly working in Tuya Smart app

## Environment

- Localtuya version:  4.1.0
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version:  2022.9.1
- [] Are you using the Home Assistant Tuya Cloud component ? NO
- [] Are you using the Tuya App in parallel ? NO

## Steps to reproduce

1. Configure the cloud account in localtuya
2. Add a new device (platform light)
3. manually add DP 24, 25
4. Color and Scene are missing, and manually added DP can not be used during configuration.
5. Trying to EDIT device and deselect main DP to cancel/clear entity, brings an unknown error.

## Configuration `configuration.yaml` or `config_flow`

Problem arises only with the last Light (Scrivania CAL) which is added with "new" version of localtuya. All the other (I left for reference) are same type of tuya light, added with old localtuya config flow
```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.9.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "5.15.60",
    "supervisor": "2022.08.6",
    "host_os": "Home Assistant OS 8.5",
    "docker_version": "20.10.14",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "meross_lan": {
      "version": "2.6.1",
      "requirements": []
    },
    "dahua": {
      "version": "0.5.0",
      "requirements": []
    },
    "nodered": {
      "version": "1.0.9",
      "requirements": []
    },
    "localtuya": {
      "version": "4.1.0",
      "requirements": []
    },
    "skyq": {
      "version": "v2.9.10",
      "requirements": [
        "pyskyqremote==0.3.16"
      ]
    },
    "hacs": {
      "version": "1.27.1",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "sql_json": {
      "version": "1.1.2",
      "requirements": [
        "sqlalchemy~=1.4.27"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "localtuya",
    "name": "LocalTuya integration",
    "version": "4.1.0",
    "documentation": "https://github.com/rospogrigio/localtuya/",
    "dependencies": [],
    "codeowners": [
      "@rospogrigio",
      "@postlund"
    ],
    "issue_tracker": "https://github.com/rospogrigio/localtuya/issues",
    "requirements": [],
    "config_flow": true,
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "region": "eu",
    "client_id": "...",
    "client_secret": "...",
    "user_id": "...",
    "username": "localtuya",
    "no_cloud": true,
    "devices": {
      "bfb800d01fb98649d8kjgh": {
        "friendly_name": "Faretto12",
        "local_key": "...",
        "host": "192.168.1.62",
        "device_id": "bfb800d01fb98649d8kjgh",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 496)",
          "24 (value: 012302d200b3)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "Faretto12",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf65560b8bd97229ac37rp": {
        "friendly_name": "Faretto13",
        "local_key": "...",
        "host": "192.168.1.63",
        "device_id": "bf65560b8bd97229ac37rp",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 496)",
          "24 (value: 012302d200b3)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "Faretto13",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf495e30d99844f9582o6n": {
        "friendly_name": "Teca alta",
        "local_key": "...",
        "host": "192.168.1.87",
        "device_id": "bf495e30d99844f9582o6n",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: white)",
          "22 (value: 10)",
          "23 (value: 0)",
          "24 (value: 000003e803e8)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "Teca alta",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bfe5461f98095ea09fqt0c": {
        "friendly_name": "Teca media",
        "local_key": "...",
        "host": "192.168.1.88",
        "device_id": "bfe5461f98095ea09fqt0c",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 1000)",
          "24 (value: 000003e803e8)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "Teca media",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bfa71764f2d4c78243ww10": {
        "friendly_name": "Teca bassa",
        "local_key": "...",
        "host": "192.168.1.89",
        "device_id": "bfa71764f2d4c78243ww10",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 1000)",
          "24 (value: 00b403e803e8)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "Teca bassa",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf11026d02a2f5ba019ez6": {
        "friendly_name": "faretto63",
        "local_key": "...",
        "host": "192.168.1.79",
        "device_id": "bf11026d02a2f5ba019ez6",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto63",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf59cfa160a47251e1ehi5": {
        "friendly_name": "faretto21",
        "local_key": "...",
        "host": "192.168.1.65",
        "device_id": "bf59cfa160a47251e1ehi5",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto21",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bfe3f13c67bed3ebc95swu": {
        "friendly_name": "faretto31",
        "local_key": "...",
        "host": "192.168.1.66",
        "device_id": "bfe3f13c67bed3ebc95swu",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto31",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf838589a7d6ea435f6327": {
        "friendly_name": "faretto32",
        "local_key": "...",
        "host": "192.168.1.67",
        "device_id": "bf838589a7d6ea435f6327",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto32",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf8e9cda0cbac549641e2p": {
        "friendly_name": "faretto33",
        "local_key": "...",
        "host": "192.168.1.68",
        "device_id": "bf8e9cda0cbac549641e2p",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto33",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bfc4c80855bd433883dm9z": {
        "friendly_name": "faretto34",
        "local_key": "...",
        "host": "192.168.1.69",
        "device_id": "bfc4c80855bd433883dm9z",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto34",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf00e5ee4885f9beedmtch": {
        "friendly_name": "faretto41",
        "local_key": "...",
        "host": "192.168.1.70",
        "device_id": "bf00e5ee4885f9beedmtch",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto41",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf6c27f480a2b73b63oz1i": {
        "friendly_name": "faretto42",
        "local_key": "...",
        "host": "192.168.1.71",
        "device_id": "bf6c27f480a2b73b63oz1i",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto42",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bfd372c487d14dc20eztva": {
        "friendly_name": "faretto43",
        "local_key": "...",
        "host": "192.168.1.72",
        "device_id": "bfd372c487d14dc20eztva",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto43",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf66648dc91f50c0e1kn6o": {
        "friendly_name": "faretto51",
        "local_key": "...",
        "host": "192.168.1.74",
        "device_id": "bf66648dc91f50c0e1kn6o",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto51",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bff163528da2d6fb31ccdv": {
        "friendly_name": "faretto52",
        "local_key": "...",
        "host": "192.168.1.75",
        "device_id": "bff163528da2d6fb31ccdv",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto52",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf8656ab32a8f0f0aeaymj": {
        "friendly_name": "faretto53",
        "local_key": "...",
        "host": "192.168.1.76",
        "device_id": "bf8656ab32a8f0f0aeaymj",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto53",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf8dc6b43916919da3v8g1": {
        "friendly_name": "faretto61",
        "local_key": "...",
        "host": "192.168.1.77",
        "device_id": "bf8dc6b43916919da3v8g1",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto61",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bff262d3181a2de1b44zrs": {
        "friendly_name": "faretto71",
        "local_key": "...",
        "host": "192.168.1.80",
        "device_id": "bff262d3181a2de1b44zrs",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto71",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf2b6e60c47fc932bcohse": {
        "friendly_name": "faretto72",
        "local_key": "...",
        "host": "192.168.1.81",
        "device_id": "bf2b6e60c47fc932bcohse",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto72",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bfb0219c46bcbff9eceedx": {
        "friendly_name": "faretto73",
        "local_key": "...",
        "host": "192.168.1.82",
        "device_id": "bfb0219c46bcbff9eceedx",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto73",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf2617f614481dbe71wbej": {
        "friendly_name": "faretto74",
        "local_key": "...",
        "host": "192.168.1.83",
        "device_id": "bf2617f614481dbe71wbej",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto74",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bff689592b8b45182ctbur": {
        "friendly_name": "faretto75",
        "local_key": "...",
        "host": "192.168.1.84",
        "device_id": "bff689592b8b45182ctbur",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto75",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bffcc77fa504cd1592zpho": {
        "friendly_name": "specchio1",
        "host": "192.168.1.85",
        "local_key": "...",
        "protocol_version": "3.3",
        "entities": [
          {
            "friendly_name": "specchio1",
            "brightness": 22,
            "color_temp": 23,
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_mode": 21,
            "color": 24,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "scene": 25,
            "music_mode": true,
            "id": 20,
            "platform": "light"
          }
        ],
        "device_id": "bffcc77fa504cd1592zpho",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "product_key": "keytg5kq8gvkv9dh"
      },
      "bf6d875d4c97b68972aej2": {
        "friendly_name": "specchio2",
        "local_key": "...",
        "host": "192.168.1.86",
        "device_id": "bf6d875d4c97b68972aej2",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 532)",
          "24 (value: 012102480080)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "specchio2",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf87eebd4d5ea130371n8v": {
        "friendly_name": "faretto11",
        "local_key": "...",
        "host": "192.168.1.61",
        "device_id": "bf87eebd4d5ea130371n8v",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: white)",
          "22 (value: 1000)",
          "23 (value: 494)",
          "24 (value: 012c02c603e8)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto11",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "music_mode": true,
            "scene": 25,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "platform": "light"
          }
        ]
      },
      "bf2b296ed38c9b97ab1yah": {
        "friendly_name": "faretto44-2",
        "local_key": "...",
        "host": "192.168.1.73",
        "device_id": "bf2b296ed38c9b97ab1yah",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: white)",
          "22 (value: 1000)",
          "23 (value: 520)",
          "24 (value: 006f03e803e8)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto44-2",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "color_temp_reverse": false,
            "music_mode": true,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "scene": 25,
            "platform": "light"
          }
        ]
      },
      "bfb9c38257dce89597y0s0": {
        "friendly_name": "faretto62-2",
        "local_key": "...",
        "host": "192.168.1.78",
        "device_id": "bfb9c38257dce89597y0s0",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: colour)",
          "22 (value: 1000)",
          "23 (value: 509)",
          "24 (value: 000003e803e8)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "faretto62-2",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "color_temp_reverse": false,
            "music_mode": true,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "scene": 25,
            "platform": "light"
          }
        ]
      },
      "bfda4aaafaf5ef3525qbwz": {
        "friendly_name": "Scorta4",
        "local_key": "...",
        "host": "192.168.1.90",
        "device_id": "bfda4aaafaf5ef3525qbwz",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: white)",
          "22 (value: 134)",
          "23 (value: 398)",
          "24 (value: 000003e803e8)",
          "25 (value: 000e0d0000000000000000c80000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "SCORTA4",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "color_temp_reverse": false,
            "music_mode": true,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "scene": 25,
            "platform": "light"
          }
        ]
      },
      "bf652265ac0133e219fkhh": {
        "friendly_name": "Scorta3",
        "local_key": "...",
        "host": "192.168.1.91",
        "device_id": "bf652265ac0133e219fkhh",
        "protocol_version": "3.3",
        "product_key": "keytg5kq8gvkv9dh",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: white)",
          "22 (value: 148)",
          "23 (value: 227)",
          "24 (value: 015a03e803e8)",
          "25 (value: 07464602000003e803e800000000464602007803e803e80000000046460200f003e803e800000000464602003d03e803e80000000046460200ae03e803e800000000464602011303e803e800000000)",
          "26 (value: 0)"
        ],
        "entities": [
          {
            "id": 20,
            "friendly_name": "SCORTA3",
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "color_temp_reverse": false,
            "music_mode": true,
            "brightness": 22,
            "color_temp": 23,
            "color_mode": 21,
            "color": 24,
            "scene": 25,
            "platform": "light"
          }
        ]
      },
      "65407401e8db84cad86f": {
        "friendly_name": "Scrivania CAL",
        "host": "192.168.1.193",
        "local_key": "...",
        "protocol_version": "3.3",
        "entities": [
          {
            "friendly_name": "Scrivania CAL",
            "brightness": 22,
            "color_temp": 23,
            "brightness_lower": 29,
            "brightness_upper": 1000,
            "color_mode": 21,
            "color_temp_min_kelvin": 2700,
            "color_temp_max_kelvin": 6500,
            "color_temp_reverse": false,
            "music_mode": false,
            "id": 20,
            "platform": "light"
          }
        ],
        "manual_dps_strings": "24,25",
        "device_id": "65407401e8db84cad86f",
        "dps_strings": [
          "20 (value: True)",
          "21 (value: white)",
          "22 (value: 1000)",
          "23 (value: 512)"
        ],
        "product_key": "ivxfweclfhvra3ym"
      }
    },
    "updated_at": "1663186091091",
    "cloud_devices": {}
  }
}
```

## Provide Home Assistant taceback/logs

```txt

```
