### ISSUE TITLE
Problem with setting up LED light and cover

### ISSUE THREAD

**Issue by darth-aragoth** [rospogrigio/localtuya#105]
Hi,
I have some problems with my Tuya devices, that work normally in SmartLife.

1. First one is LED light. I use two or even three kinds of lights, most of them work normally with localtuya (configured via YAML). One kind causes problem, It's all the time offline. It's defined like other devices:

```
  - host: some_ip
    device_id: some_id
    local_key: some_key
    friendly_name: some_name
    protocol_version: "3.3"
    entities:
      - platform: light
        friendly_name: name
        id: 1
```

It's DPS (below) is differend from other devices, so I changed ID from 20 to 1, but it didn't change anything. IP, key and ID are correct.

```
        "dps":{
          "1":false,
          "10":"ffff2e0600fff24d00ff16ff00008affff0000ffac00",
          "2":"white",
          "3":91,
          "4":178,
          "5":"6e3c000021ff6c",
          "6":"bd76000168ffff",
          "7":"ffff500100ff00",
          "8":"ffff80040000ff58ff00ff0000ffd400000000000000",
          "9":"ffff5001ff0000"
        }
```

2. Second device - blind curtain switch (https://a.aliexpress.com/_BU4g2c). I even don't know how to configure it :) I have IP, ID and local key, but in DPS I see only this:

```
        "dps":{
          "1":"3"
        }
```

In Tuya app, this device has three control buttons (up, down and pause). is it possible to control it via localtuya?

3) All my LED lamps are RGB, what have I to add to YAML configuration to see dimming, color and temperature controls? Now I can only turn them on and off.

Thank you in advance for support.
