### ISSUE TITLE
"Object of type NoneType has no len()" error for newly added tuya light when manually changing color

### ISSUE THREAD

**Issue by clemente3905** [rospogrigio/localtuya#1072]
## The problem

Hi all, I have more or less 30 tuya lights in localtuya. All of them except one where added with previous version of localtuya and work flawlessly.
Last one I tried to add with version 4.1.0 of localtuya and give me an error on DPS 24, 25 that I workaround editing /config/.storage/core.config_entries as per rospogrigio advice.

Till yesterday everything was fine.

Today if I try to change color of THIS specific light I get the error reported in the subject.

Please note that if I set a scene with changing colors, the scene is executed correctly. Problem arises only when I try to set manually a color

## Environment

- Localtuya version:  4.1.0
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version:  2022.9.7
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Open the light in Home Assistant
2. Switch to color mode
3. Try to set any color manually

## Configuration `configuration.yaml` or `config_flow`

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.10.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "5.15.67",
    "supervisor": "2022.09.1",
    "host_os": "Home Assistant OS 9.0",
    "docker_version": "20.10.17",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "meross_lan": {
      "version": "2.6.2",
      "requirements": []
    },
    "dahua": {
      "version": "0.5.0",
      "requirements": []
    },
    "nodered": {
      "version": "1.1.2",
      "requirements": []
    },
    "localtuya": {
      "version": "4.1.0",
      "requirements": []
    },
    "skyq": {
      "version": "v2.9.10",
      "requirements": [
        "pyskyqremote==0.3.16"
      ]
    },
    "hacs": {
      "version": "1.27.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "sql_json": {
      "version": "1.1.2",
      "requirements": [
        "sqlalchemy~=1.4.27"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "localtuya",
    "name": "LocalTuya integration",
    "version": "4.1.0",
    "documentation": "https://github.com/rospogrigio/localtuya/",
    "dependencies": [],
    "codeowners": [
      "@rospogrigio",
      "@postlund"
    ],
    "issue_tracker": "https://github.com/rospogrigio/localtuya/issues",
    "requirements": [],
    "config_flow": true,
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "device_config": {
      "friendly_name": "Scrivania CAL",
      "host": "192.168.1.193",
      "local_key": "7b...c7",
      "device_id": "65...6f",
      "protocol_version": "3.3",
      "product_key": "iv...ym",
      "dps_strings": [
        "20 (value: True)",
        "21 (value: white)",
        "22 (value: 1000)",
        "23 (value: 512)",
        "24 (value: 000003e803e8)",
        "25 (value: 000e0d0000000000000000c80000)",
        "26 (value: 0)"
      ],
      "entities": [
        {
          "id": 20,
          "friendly_name": "Scrivania CAL",
          "brightness_lower": 29,
          "brightness_upper": 1000,
          "color_temp_min_kelvin": 2700,
          "color_temp_max_kelvin": 6500,
          "color_temp_reverse": false,
          "music_mode": false,
          "brightness": 22,
          "color_temp": 23,
          "color_mode": 21,
          "color": 24,
          "scene": 25,
          "platform": "light"
        }
      ]
    }
  }
}
```

## Provide Home Assistant taceback/logs

```txt
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.localtuya.light
Source: custom_components/localtuya/pytuya/__init__.py:150
Integration: LocalTuya (documentation, issues)
First occurred: 18:39:33 (11 occurrences)
Last logged: 18:43:54

[65...6f] Entity light.scrivania_cal is requesting unknown DPS index 24
```
## Additional information

Linked to [https://github.com/rospogrigio/localtuya/issues/1033](url)
