### ISSUE TITLE
Need help with Vaccum: Mellerware City Move

### ISSUE THREAD

**Issue by antonio1475** [rospogrigio/localtuya#1100]
I've spent hours on this, so time to ask for help...
## The problem
I have a Mellerware City Move vacuum, which is a local company but must be a re-branded chineses one as usual.
The device came with its own app, but works with Tuya. The only downside is that the 3 Fan Speeds are all "1.0" and Return to base is just "findsta", but otherwise it works.

With Tuya Cloud integration, it appears as a simple switch that does nothing.
With Local Tuya, after hours of doing the steps from other issues / posts (especially [Finding Tuya Data Points](https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html)) , I got something to work, but it's pretty random and some key things (eg. Return to base) are not working.

## Environment
- Localtuya version: 4.1.1
- Home Assistant Core version:  
- [x] Are you using the Home Assistant Tuya Cloud component ?
- [x] Are you using the Tuya App in parallel ?

## Steps to reproduce

1. [Find Tuya Data Points](https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html)
2. Play around and compare values with Tuya IoT Log. I've noted down all the Data Points, seen values in the log, as well as the results from testing many DPs and values with the set_dp service: https://docs.google.com/spreadsheets/d/1DFQ8O7qEJWEU0tZ62e1q0LTGmynt-0mORSXVb58YqbA/edit?usp=sharing
3. Set the DPs in Local Tuya config (tried multiple combinations).

Right now, 
- [ ] Status is always "Cleaning"
- [ ] Play button does nothing
- [x] Pause button works
- [ ] Stop button starts the vacuum (❓)
- [ ] Locate doesn't work (don't care)
- [ ] Return home doesn't work
- [ ] Return to Dock doesn't work
- [x] Fan speed works
- [x] Cleaning mode (attribute) updates properly
- [x] Clean time (attribute) updates properly
- [x] Clean area (attribute) updates properly

## Configuration `configuration.yaml` or `config_flow`
<details>
  <summary>Device diagnostics. Click to expand</summary>
  
  ```js
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.10.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Madrid",
    "os_name": "Linux",
    "os_version": "5.15.67",
    "supervisor": "2022.10.0",
    "host_os": "Home Assistant OS 9.0",
    "docker_version": "20.10.17",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "samsungtv_smart": {
      "version": "0.7.8",
      "requirements": [
        "websocket-client!=1.4.0,>=0.58.0",
        "wakeonlan>=2.0.0",
        "aiofiles>=0.8.0"
      ]
    },
    "browser_mod": {
      "version": "2.1.2",
      "requirements": []
    },
    "spotcast": {
      "version": "v3.6.30",
      "requirements": [
        "spotify_token==1.0.0"
      ]
    },
    "tapo_control": {
      "version": "4.1.3",
      "requirements": [
        "pytapo==2.5",
        "onvif-zeep-async==1.2.0"
      ]
    },
    "amazon_rekognition": {
      "version": "3.4.0",
      "requirements": [
        "pillow",
        "boto3>=1.9.69"
      ]
    },
    "ui_lovelace_minimalist": {
      "version": "v1.1.5",
      "requirements": [
        "aiofiles==0.8.0",
        "aiogithubapi>=22.2.4"
      ]
    },
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "localtuya": {
      "version": "4.1.1",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "localtuya",
    "name": "LocalTuya integration",
    "version": "4.1.1",
    "documentation": "https://github.com/rospogrigio/localtuya/",
    "dependencies": [],
    "codeowners": [
      "@rospogrigio",
      "@postlund"
    ],
    "issue_tracker": "https://github.com/rospogrigio/localtuya/issues",
    "requirements": [],
    "config_flow": true,
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "device_config": {
      "friendly_name": "City Move DP",
      "host": "192.168.3.17",
      "local_key": "xxx",
      "protocol_version": "3.3",
      "scan_interval": 60,
      "manual_dps_strings": "101,102,104,105,107,14,109,110,111,110,17,116,117",
      "entities": [
        {
          "friendly_name": "Aspirador DP",
          "idle_status_value": "STANDBY,STANDBY_STA,HALTING,HALTING_STA,CHARGING,CHARGING_STA",
          "powergo_dp": 1,
          "docked_status_value": "CHARGING,CHARGING_STA",
          "returning_status_value": "findsta,FIND_STA",
          "battery_dp": 108,
          "mode_dp": 117,
          "modes": "AUTO,RANDOM,EDGE",
          "return_mode": "find",
          "fan_speed_dp": 104,
          "fan_speeds": "FANHALTING,FANNORAM,FANMAX",
          "clean_time_dp": 107,
          "clean_area_dp": 14,
          "locate_dp": 116,
          "fault_dp": 17,
          "paused_state": "STANDBY,HALTING",
          "stop_status": "0",
          "id": 1,
          "platform": "vacuum"
        }
      ],
      "device_id": "bf4ac5c80b11f315d54w8l",
      "dps_strings": [
        "1 (value: False)",
        "14 (value: 47)",
        "17 (value: 0)",
        "101 (value: HALTING)",
        "102 (value: null)",
        "104 (value: FANMAX)",
        "105 (value: stop)",
        "107 (value: 3)",
        "108 (value: 13)",
        "109 (value: 85)",
        "110 (value: 93)",
        "111 (value: -1)",
        "116 (value: -1)",
        "117 (value: -1)"
      ],
      "product_key": "sayafukjeqp9kupy"
    }
  }
}
  ```
</details>

## DP dump
DP dump gives me the following error. Am I missing something?
```
Traceback (most recent call last):
  File "C:\Users\anton\Desktop\tuyadebug\test.py", line 12, in <module>
    import localtuya
  File "C:\Users\anton\Desktop\tuyadebug\localtuya\__init__.py", line 41, in <module>
    from cryptography.hazmat.backends import default_backend
ModuleNotFoundError: No module named 'cryptography'
```

Tuya IoT Platform Get Device Specification Attribute (both) only gives this small thing with no DPs, which I guess is a big part of the problem:
```
{
  "result": {
    "category": "sd",
    "functions": [
      {
        "code": "power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fault",
        "dp_id": 17,
        "type": "Bitmap",
        "values": "{\"label\":[\"edge_sweep\",\"middle_sweep\",\"left_wheel\",\"right_wheel\",\"garbage_box\",\"land_check\",\"collision\"]}"
      }
    ]
  },
  "success": true,
  "t": 1666561162132,
  "tid": "282425b4531b11eda7bed2b5cc5248de"
}
```

![image](https://user-images.githubusercontent.com/63130724/197420540-4c72daed-0d31-4563-ac3d-91cc0073692c.png)
![image](https://user-images.githubusercontent.com/63130724/197420575-c0894eca-2642-4d94-acad-01d9c8188947.png)

**Comment by antonio1475** [comment]
Re-adding the device with the right DP ID (101, which showed in the logs STANDBY/CLEANING/CHARGING solved the status issue. I was wondering what DP defined the status. Looking at the vacuum.py code helped me figure out that it was the self ID DP.

![image](https://user-images.githubusercontent.com/63130724/197421558-9ebf2c8b-cefa-4090-a5dd-e4f103c814bb.png)

For the rest of the issues like Start/Stop/Return to base, I can make use of Tuya Scenes. Not ideal but same result 😀

**Comment by antonio1475** [comment]
Just leaving this here in case someone finds themselves in a similar situation.
Made some more testing and achieved a mostly working configuration! 😀 

1. **localtuya config**: This is the best localtuya config I could achieve.
Most buttons mostly work (sometimes Play/Pause/Stop need a certain current status to work). Locate doesn't (check point 2).

<details><summary>Click to expand</summary>

![backup aspirador working v2_pages-to-jpg-0001](https://user-images.githubusercontent.com/63130724/198029964-d2e7dd1a-17ad-40cc-b9c5-8da8ac0c686a.jpg)

```
  "data": {
    "device_config": {
      "friendly_name": "Aspirador v3",
      "host": "192.168.3.17",
      "local_key": "xxxxx",
      "protocol_version": "3.3",
      "scan_interval": 60,
      "manual_dps_strings": "101,102,104,105,107,14,109,110,111,110,17,116,117",
      "entities": [
        {
          "friendly_name": "Aspirador",
          "idle_status_value": "STANDBY",
          "powergo_dp": 102,
          "docked_status_value": "CHARGING_STA,CHARG_COMP",
          "returning_status_value": "FIND_STA",
          "battery_dp": 108,
          "mode_dp": 102,
          "modes": "clean_auto,clean_random,clean_wall,clean_spot",
          "return_mode": "find_sta",
          "fan_speed_dp": 104,
          "fan_speeds": "FANHALTING,FANNORAM,FANMAX",
          "clean_time_dp": 107,
          "clean_area_dp": 14,
          "clean_record_dp": 14,
          "locate_dp": 116,
          "fault_dp": 17,
          "paused_state": "HALTING",
          "stop_status": "STOP",
          "id": 101,
          "platform": "vacuum"
        }
      ],
      "device_id": "bf4ac5c80b11f315d54w8l",
      "dps_strings": [
        "1 (value: False)",
        "14 (value: 0)",
        "17 (value: 0)",
        "101 (value: CHARGING_STA)",
        "102 (value: null)",
        "104 (value: FANHALTING)",
        "105 (value: stop)",
        "107 (value: 0)",
        "108 (value: 33)",
        "109 (value: 84)",
        "110 (value: 92)",
        "111 (value: -1)",
        "116 (value: -1)",
        "117 (value: -1)"
      ],
      "product_key": "sayafukjeqp9kupy"
    }
  }
}
````

</details>

3. **Use [Vacuum Card](https://github.com/denysdovhan/vacuum-card)** to overwrite the actions, since localtuya sends some incorrect DP values for this vacuum, and displaying some info in the right units like clean_area (needs to be divided by 10):

![image](https://user-images.githubusercontent.com/63130724/198019466-369b8190-4cd9-4475-aa82-e2303a96e188.png)

<details><summary>Click to expand card yaml</summary>

```
type: custom:vacuum-card
entity: vacuum.aspirador
image: default
compact_view: false
show_name: true
show_status: true
show_toolbar: true
actions:
  start:
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 102
      value: clean_auto
  pause:
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 1
      value: pause
  stop:
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 1
      value: stop
  locate:
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 116
      value: true
  return_to_base:
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 102
      value: find_sta
stats:
  default:
    - value_template: >-
        {{ (states.vacuum.aspirador.attributes.clean_area | float(0) / 10) |
        round(1) }}
      unit: m²
      subtitle: Cleaned area
    - attribute: clean_time
      unit: minutes
      subtitle: Cleaning time
    - subtitle: Mode
      value_template: >-
        {% set mode = states.vacuum.aspirador.attributes.cleaning_mode %} {% if
        mode == 'clean_auto' %} Auto {% elif mode == 'clean_random' %} Random {%
        elif mode == 'clean_wall' %} Wall {% elif mode == 'clean_spot' %} Spot
        {% else %} N/A {% endif %}

```

</details>

Everything basically works (especially with vacuum-card) and the only things I'm missing are:

1. Fan speeds to have normal names instead of FANHALTING, FANNORAM and FANMAX (eg. Min, Medium, Max). Maybe setting up "aliases" somehow/somewhere? Not sure.

2. Ability to choose Cleaning mode. I'm not sure if I'm supposed to expect a dropdown list like the fan speed? The Mode DP is set, the Modes list is set, and doing it through Dev Tools Service works (DP 102 or 117). I only found [issue 762](https://github.com/rospogrigio/localtuya/issues/762) on this.

@rospogrigio anything I can do for any of the 2 points? I am fully aware that this is not a common device, so not really expecting much, I can work around this :)
Thanks a lot
