### ISSUE TITLE
help with the integration

### ISSUE THREAD

**Issue by userMak** [rospogrigio/localtuya#113]
Hi
I have added one of my devices through the integration localtuya. Now I want to add one more. 
How can I added because I don't see an option there. Should I use the configuration.yaml??

**Comment by darth-aragoth** [comment]
Try to use (+) button (yellow in dark theme) in configuration --> integrations, then choose 'LocalTuya integration'. Or you can use YAML.

**Comment by userMak** [comment]
Thanks. Can you help me to add my covers please?
My first question is since the localtuya has discover them meaning that they can work?
I tried the following but the entity does not respond

![cover1](https://user-images.githubusercontent.com/55662933/96987001-13821000-152b-11eb-8fb5-5104f30c384a.jpg)

**Comment by darth-aragoth** [comment]
Try to set Open/Close Commands to 1_2_3 and try if it works. If yes - you can set Positioning mode to Fake, measure time needed to full close curtain (from full-open, in seconds) and enter it in last field.

**Comment by userMak** [comment]
For the time being I can not use them. I tried some variations but I am not sure what I am doing at all.
Can you confirm (do you know) that since they are discovered they will work (with the appropriate setup) or not?
and one more question. I have added the positioning mode when testing and now there is not an option to remove it. Is this normal? I also trying to remove only this device and I don't know how. Do you?

![how to](https://user-images.githubusercontent.com/55662933/96989264-1e8a6f80-152e-11eb-9037-d4ef9e18dea3.jpg)

**Comment by userMak** [comment]
![position](https://user-images.githubusercontent.com/55662933/96989454-5c879380-152e-11eb-86e5-4a11d2fd6a90.jpg)

**Comment by darth-aragoth** [comment]
I think you have old version that doesn't support 1/2/3 controllers. Try to update to `master`. Leave the Current position and Set position empty. And I assume that IP, device ID and localkey are entered correct?

**Comment by userMak** [comment]
Sorry for my limited knowledge. I don't understand what you mean to update to master?

Yes the ip and id local key are correct.

**Comment by darth-aragoth** [comment]
You can remove existsing devices from Configuration --> Integrations panel. There should be LocalTuya integration box, there you can select desired device and delete it.

Select device:
![image](https://user-images.githubusercontent.com/72323164/96990655-acaf2780-1527-11eb-9d01-a2d869ab33dd.png)

and delete it from menu:
![image](https://user-images.githubusercontent.com/72323164/96990570-94d7a380-1527-11eb-87e8-30f7501dda12.png)

**Comment by darth-aragoth** [comment]
Try the following steps :)
![image](https://user-images.githubusercontent.com/72323164/96991027-28a96f80-1528-11eb-8903-33c0c58138a6.png)

**Comment by userMak** [comment]
and place it in custom components folder?

**Comment by darth-aragoth** [comment]
Exctract ZIP archive and copy directory `localtuya-master/custom_components/localtuya` to `/config/custom_components`. In HA you should have `/config/custom_components/localtuya` directory with two subdirectories and a few files inside.

**Comment by userMak** [comment]
Hey, it is working!! with the 1_2_3
Thanks a lot. I would never done it without your help

**Comment by darth-aragoth** [comment]
No problem :)

**Comment by userMak** [comment]
> No problem :)

Hi 
I have added 3 of my covers successfully but I did something wrong I guess and when I tried to add the 4th it didn't worked.
I restarted HA - I readded it - and it is in status unavailable. I tried to add the 5th and I got an error in the logs.. 
Any idea what to do please?

`Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:593
Integration: LocalTuya (documentation, issues)
First occurred: 2:23:18 PM (1 occurrences)
Last logged: 2:23:18 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 236, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 164, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 593, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.29', 6668)`

**Comment by darth-aragoth** [comment]
Are you sure IP / ID / key are correct? Can you control them via Tuya app?

**Comment by darth-aragoth** [comment]
If yes - try restarting controllers (disconnect from power for a while) and restart HA.

**Comment by userMak** [comment]
Yes I can control them from tuya app
I am trying to disconnect them now. I will let you know.
When you say disconnect you mean to cut the electricity power. correct?

**Comment by darth-aragoth** [comment]
Yes, It's the easiest way.

**Comment by userMak** [comment]
ok. let me see

**Comment by userMak** [comment]
No, I have done something wrong. maybe by mistake it is declared as a sensor and it won't "forget" it.
I tried after the cut of the power and when I click to submit it tells me : An unknown error occurred. See log for details.
`Log Details (ERROR)
Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:510
Integration: LocalTuya (documentation, issues)
First occurred: 2:44:12 PM (1 occurrences)
Last logged: 2:44:12 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 236, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 171, in validate_input
    detected_dps = await interface.detect_available_dps()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 466, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 428, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 413, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in _decode_payload
    raise Exception(f"Unexpected payload={payload} (id: {self.id})")
Exception: Unexpected payload=b'json obj data unvalid' (id: 50758014840d8e91f4fd)`

**Comment by userMak** [comment]
for example in my next try I try to add my dimmer and although I changed the ip the name and local key was kept from the previous cover.. I sure did something wrong sometime

**Comment by darth-aragoth** [comment]
Try to delete wrong device like shown on pictures above.

**Comment by userMak** [comment]
I have but it keeps them. I added my dimmers and they are ok. When I try to add my 2 (last) covers it showing that 
"An unknown error occurred. See log for details."

my patient is limited :(

**Comment by darth-aragoth** [comment]
I don't have any idea why you can't delete them. I can do it without any problem.

BTW I think much easier is managing localtuya devices via yaml. Using Excel in a few minues I created script that added about 40 devices to HA at once.

**Comment by userMak** [comment]
Well as you noticed I am not that good with coding :) That's why I am trying through integration.
I think I saw somewhere tha HA keeps file with the entities. I think that somehow it has created the entities for these to ip's?

**Comment by darth-aragoth** [comment]
You can check `/config/.storage/core.config_entries`, but I don't know if it's the right place - I have never had to change it manually.

**Comment by userMak** [comment]
I did. nothing is there except my correct devices of localtuya.
Can you give me an example of the configuration.yaml for covers with the 1/2/3 option because I don't know how to add it?
from the example I have right now
`localtuya:
  - host: 192.168.1.27
    device_id: xxxx
    local_key: xxxx
    friendly_name: window main
    protocol_version: "3.3"
    entities:
      - platform: cover
        friendly_name: Device Cover
        id: 2
        open_close_cmds: "open_close"
        positioning_mode: "fake"
        span_time: 25`

**Comment by darth-aragoth** [comment]
Example with switch, cover and light:

```
localtuya:
  - host: some_ip
    device_id: some-id
    local_key: some-key
    friendly_name: Switch device name
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: Switch entity name
        id: 1
        current: 4
        current_consumption: 5
        voltage: 6
      - platform: sensor
        friendly_name: Current entity name
        id: 4
        scaling: 0.001
        device_class: current
        unit_of_measurement: "A"
      - platform: sensor
        friendly_name: Power entity name
        id: 5
        scaling: 0.1
        device_class: power
        unit_of_measurement: "W"
      - platform: sensor
        friendly_name: Voltage entity name
        id: 6
        scaling: 0.1
        device_class: voltage
        unit_of_measurement: "V"
  - host: ip
    device_id: id
    local_key: key
    friendly_name: Cover device name
    protocol_version: "3.3"
    entities:
      - platform: cover
        friendly_name: Cover device entity
        id: 1
        commands_set: "1_2_3"
        positioning_mode: "fake"
        span_time: 16.8
  - host: ip
    device_id: id
    local_key: key
    friendly_name: Light device name
    protocol_version: "3.3"
    entities:
      - platform: light
        friendly_name: Light device entity
        id: 20
```

You have a nice example in localtuya-master/README.md
