### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Nunsferatus** [rospogrigio/localtuya#1133]
Let me start by saying that I'm a NOOB.

I've been trying to configure the sensors that I have in one of my plugs. I have tried everything that I could think of and I always get some kind of error. I'm really stuck and out of ideas. can anyone help me?
It seems to work correctly in the template…
![image](https://user-images.githubusercontent.com/83787364/202860960-a160cf8d-9d69-46b3-8663-d4fc47b04df9.png)

Thanks for the help

**Comment by Santanachia** [comment]
don't use states.switch.plant_lights.voltage, use this instead:
```yaml
state_attr('switch.plant_lights', 'voltage')
```

p.s. it is better when you copy the code than upload a photo.

**Comment by Nunsferatus** [comment]
Thank you for your help.



I have made the adjustment that you suggested

now I'm getting an error saying “duplicate key”

Doing this in the configuration.yaml Is this the correct place?



Once again thank you.

He is the code:

sensor:
    - platform: template
      sensors:
        switch.plant_lights_voltage:
          value_template: >-
            {{ state_attr('switch.plant_lights', 'voltage') }}
          unit_of_measurement: 'V'


        switch.plant_lights_current:
              value_template: >-
                {{ state_attr('switch.plant_lights', 'current') }}
              unit_of_measurement: 'mA'


        switch.plant_lights_current_consumption:
              value_template: >-
                {{ state_attr('switch.plant_lights', 'consumption') }}
              unit_of_measurement: 'W'

**Comment by Santanachia** [comment]
maybe it's just my subjective impression, but this code looks strange to me.
In my case the custom sensor looks like this:
```yaml
template:
  - sensor:
    - name: "Socket Voltage"
      state: "{{ float(states('sensor.smart_socket_voltage'), 0) / 10 }}"
      unique_id: madre_gniazdkoV
      unit_of_measurement: V
```
