### ISSUE TITLE
Support for RGB IC light strip and not discovered DPS from the test.py script

### ISSUE THREAD

**Issue by tommicarraro** [rospogrigio/localtuya#1354]
## The problem

- The light's behavior is not supported by localtuya. The leds of the strip can individually be controlled from the tuya app, but they require a Dreamlight scene mode, and the actual scene defined are not working.
- Some DPS are not discovered by the debugging script, but in the Tuya iot Platform - Device Debugging Console are present and they are perfectly working.

### Device Informations
Product Name: WIFI幻彩灯带
Product Category: dd

From the product category, it seems that the instruction set is the following: [https://developer.tuya.com/en/docs/iot/strip-lights?id=Kaof81gv0qj9i](https://developer.tuya.com/en/docs/iot/strip-lights?id=Kaof81gv0qj9i)

## DP dump and missing DPS
```
dev_type type_0a:
    DPS [20] VALUE [True] -> ON/OFF 
    DPS [21] VALUE [scene] -> Mode 
    DPS [22] VALUE [380] -> Brightness 
    DPS [23] VALUE [105] -> Color Temp 
    DPS [24] VALUE [003c03e8000c] -> Color 
    DPS [25] VALUE [000e0d0000000000000000c80000] -> Scene
    DPS [26] VALUE [0] -> Timer 
    DPS [53] VALUE [3] -> Strip light pixel number set
```
Missing DPS that the test.py script is not able to discover but are present on the tuya iot "Device Debugging" console.
To get them, I've followed the tutorial that Zigbee2MQTT.io provides at: [https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#_8-find-your-data-point](https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#_8-find-your-data-point)

and the data found are confirmed by official API through Postman [https://developer.tuya.com/en/docs/iot/set-up-postman-environment?id=Ka7o385w1svns](https://developer.tuya.com/en/docs/iot/set-up-postman-environment?id=Ka7o385w1svns)
```
    DPS [27] -> Music
    DPS [28] -> Adjust
    DPS [31] -> Fall Asleep
    DPS [32] -> Wake up
    DPS [33] -> Power memory
    DPS [34] -> Do not disturb mode
    DPS [51] -> Dreamlight scene mode
    DPS [52] -> Dreamlight built-in music sync
```

## What is working, and what not with localtuya:
| **Mode** | **Code on Tuya** |  **DP** |  **Type** |  **Values** |  **Supported?** |
|--- |--- |--- |--- |--- |--- |
| ON/OFF |  switch_led  |  20  |  Boolean  |  "{true,false}"  |  Yes  |
|  Mode  |  work_mode  |  21  |  Enum  |  {"range": ["white","colour","scene","music"]}  |  Yes (is setted)  |
|  Brightness  | bright_value  |  22  | Integer  | {"min": 10,"max": 1000,"scale": 0,"step": 1}  |  Yes |
|  Color Temp   | temp_value  |  23  | Integer  | {"min": 0,"max": 1000,"scale": 0,"step": 1}  |  Yes |
|  Color  | colour_data  |  24  | String  | {"maxlen": 255}  |  Yes  |
|  Scene  |  scene_data |  25  | String  | {"maxlen": 255}  |  **No (see below "Dreamlight scene mode")**  |
|  Timer  | countdown  |  26  | Integer  | {"unit": "s","min": 0,"max": 86400,"scale": 0,"step": 1}  | **No**  |
|  Music  | music_data  |  27  | String  | {"maxlen": 255}  | **No (see below "Dreamlight built-in music sync")**  |
|  Adjust  | control_data  |  28  | String  | {"maxlen": 255}  | **No**  |
|  Fall Asleep  | sleep_mode  |  31  | Raw  | {"maxlen": "255"}  | **No**  |
|  Wake up  | wakeup_mode  |  32  | Raw  | {"maxlen": "255"}  | **No**  |
|  Power memory  | power_memory  |  33  | Raw  | {"maxlen": "255"}  | **No**  |
|  Do not disturb mode  | do_not_disturb |  34  |  Boolean  |  "{true,false}"  |  **No**  |
|  Dreamlight scene mode | dreamlight_scene_mode  |  51  | Raw  | {"maxlen": "255"}  | **No: all the light effects from the remote and from the tuya app are codified here**  |
|  Dreamlight built-in music sync  | dreamlightmic_music_data  |  52  | Raw  | {"maxlen": "255"}  | **No: all the music effects from the remote and from the tuya app are codified here**  |
|  Strip light pixel number set  | lightpixel_number_set  |  53  | Integer  | {"min": 1,"max": 1000,"scale": 1,"step": 1}  |  **No** |

### Dreamlight scene mode
| **Mode on the app** | **Code** | 
|--- |--- |
| Quiet - Film |  AQAAAAAAAABkAAAA | 
| Quiet - Dating |  AQEAAAAAAABkACFk  | 
| Quiet - Sunset | AQIAAACgAABkAB5QADxQABJV  | 
| Quiet - Christmas Eve | AQMAAACAAABkAPBkAD1kAABkAK5kARNkAHhk  | 
| Active - Romantic |  AQQBKCgAAABkACMXAJJXAHgy | 
| Active - Colorful |  AQUDZGQAAABkAABkAHhkAPBkAD1kAK5kARNk | 
| Active - Dynamic |  AQYEZGQAAABkAABkADxkAHhkALRkAPBkASxk | 
| Active - Dream |  AQcBPDwAAABkAQRQARhGARNk | 
| Marquee - Rainbow | AQgLMjKAAABkAABkAB5kADxkAHhkALRkAPBkASxk | 
| Marquee - Flowing Water | AQkKMjKgAABkAABkADxkAHhkALRkAPBkASxk | 

### Dreamlight built-in music sync 
| **Mode on the app** | **Code** | 
|--- |--- |
| Rhythm |  AQEAAzIyAAAAZAAAZAB4ZADwZAA8ZAC0ZAEsZAAAAA== | 
| Roll |  AQEBAjIyAQAAZAAAZAB4ZADwZAA8ZAC0ZAEsZAAAAA==  | 
| Energy | AQECADIyAQAAZAAAZAB4ZADwZAA8ZAC0ZAEsZA==  | 
| Spectrum | AQEDEDIyAQAAZAAAZAB4ZADwZAA8ZAC0ZAEsZAAAAA==  |

**Comment by TheWiseWolfy** [comment]
I am slowly unfolding the actual encoding of the Dreamlight scene mode format



```
def encode_simple_custom_base64(value):
    characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    value = max(1, min(value, 64))
    encoded_char = characters[value - 1]
    return encoded_char


def encode_custom_base64(value):
    value = max(1, min(value, 100))
    quotient, remainder = divmod(value , 64)
    encoded_char = encode_simple_custom_base64(quotient) + encode_simple_custom_base64(remainder)
    return encoded_char

def main(name):
    header = "AckAZGT" - related to static dreamlight mode
    header += "A"  # color transition 
    header += "AA" # probably another setting
    header += encode_custom_base64(50) #brighness
    R = 60 #saturation
    G = 12 #color wheel value
    B = 64 #not very clear
    for i in range(15):
        header += 'A'
        header += encode_simple_custom_base64(G)
        header += encode_simple_custom_base64(R)
        header += encode_simple_custom_base64(B)
    print(insert_text_in_main_body(header))

```

**Comment by rialDave** [comment]
I'm not quite sure but I think I've got at least a similar or maybe the same problem. If that's not on topic let me know.

It's a tuya controllable RGBIC strip, which doesn't seem to work correctly for me. I'm attaching some screenshots from my app and available configuration here, maybe that helps! Would love to see this integrated in local tuya correctly.

From what your "modes" (seems to be called "dynamic_mod" in the API) are saying these seem to be different ones to mine tho, being:
* Breath
* Flash
* Jump
* Gradient
* Symphony
* Trail
* Popular
* Stacking
* Adjoint

Also I can choose from the following "scenes" in the app:
* Reading
* Get Up
* Good Night
* Starr(..something not readable)
* Party
* Film

Besides that I have the option for "dimmer" (just a color selection), "music" and "timer".

If there's anything else I could read from the Tuya IoT explorer that helps, let me know.

<img src="https://github.com/rospogrigio/localtuya/assets/8640758/f1afb146-e50b-4371-88e6-e4e521ed2e20" width="300px">
<img src="https://github.com/rospogrigio/localtuya/assets/8640758/ffe6f244-7799-4530-846d-fd95f7ca9fd5" width="300px">

**Comment by heijligers** [comment]
Hi everyone. I'm also interested in taking full control of this led light strip. Please DM when you've had any success in setting indivudal segments through python/homeassistant control.
Thanks!

**Comment by rriverob** [comment]
Hi, Im having the same issue (I think):  LocalTuya: Detected most of  my devices but one RGB Strip is not discovered. I tried to add it manually but I got this message: Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists.

**Comment by heijligers** [comment]
I went on a little wild goose chase in trying to reverse engineer the individual segment control... No luck so far, but maybe it inspires one of you to the correct path.:
https://chat.openai.com/share/69b96cbf-b258-4786-ab53-56b8b650ef59

![CleanShot 2024-02-06 at 00 35 48@2x](https://github.com/rospogrigio/localtuya/assets/3141847/ef3adf07-c889-4aa9-b3e5-60ecc157d0db)

**Comment by ArcaneTemplar13** [comment]
Also watching this in hopes for a solution. If only it was possible to flash WLED on the majority of these controllers!

**Comment by thestumonkey** [comment]
following as same issue

**Comment by thestumonkey** [comment]
Looks like tuya has documented the protocol for this!  https://developer.tuya.com/en/docs/iot/sdk?id=Kbhjudllricrx
Odd issue is that DP 58 (number of LEDs) is not exposed, but I suppose this is perhaps set via the hardware and isn't something we'd need to play with.

**Comment by thestumonkey** [comment]
Also looks like there's some code on how to make scenes, but it's beyond my coding ability:  https://github.com/tuya/tuya-panel-demo/tree/main/examples/lampLightString

**Comment by CmdrAvegan** [comment]
Device Interpretation
The LED device expects commands in a specific format, which includes:

Segment Identifier: Identifies which segment of the LED strip the command applies to.

HSV Color Information: Specifies the color using Hue, Saturation, and Value (brightness) in predefined ranges.

Payload Structure: A sequence of bytes that includes the segment identifier and the HSV color values, formatted in a specific way.

Key Concepts:
Hue: A degree on the color wheel (0-360).

Saturation: The intensity of the color (0-1000).

Value: The brightness of the color (0-1000).

Example of the Process:

RGB to HSV Conversion:

The chosen RGB color is converted to HSV format using the formula:

python
hsv = colorsys.rgb_to_hsv(r/255.0, g/255.0, b/255.0)
hue = int(hsv[0] * 360)
sat = int(hsv[1] * 1000)
val = int(hsv[2] * 1000)
Hexadecimal Conversion:

The HSV values are converted to a 12-digit hexadecimal string:

python
hex_values = [self.convert_dec_to_hex(hue, 4), self.convert_dec_to_hex(sat, 4), self.convert_dec_to_hex(val, 4)]
hsv_hex = ''.join(hex_values)
Construct Payload:

The original payloads are reused to ensure the segment control structure is correct. Example:

python
original_payloads = [
    b'\x00\x02\x00\x14\x01\x00\x00\x03\xe8\x03\xe8\x81\x14',
    b'\x00\x02\x00\x14\x01\x00\x00\x03\xe8\x03\xe8\x81\n',
    b'\x00\x02\x00\x14\x01\x00\x00\x03\xe8\x03\xe8\x81\t',
    # ... other segments ...
]
byte_array = bytearray(original_payloads[segment - 1])
byte_array[5:11] = bytearray.fromhex(hsv_hex)  # Insert the HSV values
Base64 Encoding and Sending:

The modified payload is base64-encoded and sent to the device:

python
modified_value = base64.b64encode(byte_array).decode('utf-8')
d.set_value('61', modified_value)
Real-World Example:
Scenario: Setting the first segment to a red color.

RGB Color: (255, 0, 0)

Converted HSV: (Hue=0, Sat=1000, Val=1000)

Hexadecimal HSV: '000003E803E8'

Payload Before Modification: b'\x00\x02\x00\x14\x01\x00\x00\x03\xe8\x03\xe8\x81\x14'

Payload After Inserting HSV: b'\x00\x02\x00\x14\x01\x00\x00\x00\x00\x03\xe8\x14' (where the color values are updated)

Base64-Encoded Payload: 'AAIAFAEAAAAAA+gU'

Scenario: Setting the second segment to a green color.
RGB Color: (0, 255, 0)

Converted HSV: (Hue=120, Sat=1000, Val=1000)

Hexadecimal HSV: '007803E803E8'

Payload Before Modification:

python
b'\x00\x02\x00\x14\x01\x00\x00\x03\xe8\x03\xe8\x81\x13'
Payload After Inserting HSV:

python
b'\x00\x02\x00\x14\x02\x00\x78\x03\xe8\x03\xe8\x13'
Base64-Encoded Payload:

python
'AAIAFAIAAHgD6OsT'
The device receives this encoded payload, decodes it, and applies the green color to the second segment.

Another Scenario: Setting a different segment to the same red color as the first.
Segment: Third segment

RGB Color: (255, 0, 0)

Converted HSV: (Hue=0, Sat=1000, Val=1000)

Hexadecimal HSV: '000003E803E8'

Payload Before Modification:

python
b'\x00\x02\x00\x14\x01\x00\x00\x03\xe8\x03\xe8\x81\x12'
Payload After Inserting HSV:

python
b'\x00\x02\x00\x14\x03\x00\x00\x03\xe8\x03\xe8\x12'
Base64-Encoded Payload:

python
'AAIAFAMAAAAAA+gS'

The device receives this encoded payload, decodes it, and applies the color to the specified segment.

**Comment by drunkly** [comment]
This is the information I could get until some try an error:
hh nn hh hh mm hh hh ll ll vv vv qq pp
h = header
n = mode 2(01 normal / 02 degraded)
m = mode (02 postion led off/01 position led on /00 all led )
h = hue
l = sat
v = val
p = position
qq = coloring mode (00 =from second led until pp led / 81 only selected pp led)

it would be great if this is documented somewhere so we can now what infomration is expected.
I also share a script I'm using to color the strip led depending on solar panels in case someone is interested in:

configuration.yaml
```
shell_command:
  - rgbic: sudo /usr/local/bin/rgbic {{production}} {{consumption}}
```

automation on homeassistant:
```
alias: solar
description: ""
triggers:
  - trigger: time_pattern
    minutes: /5
    enabled: false
  - trigger: state
    entity_id:
      - binary_sensor.solar_consumption_high
    to: "on"
  - trigger: state
    entity_id:
      - sensor.envoy_produccion_actual_de_energia
conditions:
  - condition: numeric_state
    entity_id: sensor.envoy_produccion_actual_de_energia
    above: 0.16
  - condition: not
    conditions:
      - condition: state
        entity_id: binary_sensor.sapito_puerta
        state: "on"
actions:
  - action: script.update_solar
    metadata: {}
    data: {}
mode: single
```
script update:
```
sequence:
  - action: shell_command.rgbic
    metadata: {}
    response_variable: rgbic
    data:
      production: >-
        {{ (states('sensor.envoy_produccion_actual_de_energia') |
        float(default=2.4)) * 1000 | round(0) | int }}
      consumption: >-
        {{ (states('sensor.envoy_consumo_actual_de_energia') |
        float(default=1.0)) * 1000 | round(0) | int }}
  - action: telegram_bot.send_message
    metadata: {}
    data:
      target: *********
      message: >-
        Este fue el resultado de rgbic: {{ '

        ' -}} consumo: {{ (rgbic['stdout'] | from_json)['consumo']  }} {{ '

        ' -}} produccion: {{ (rgbic['stdout'] | from_json)['produccion']  }} {{
        '

        ' -}} azul: {{ (rgbic['stdout'] | from_json)['azul']  }} {{ '

        ' -}} naranja: {{ (rgbic['stdout'] | from_json)['naranja']  }} {{ '

        ' -}} rojo: {{ (rgbic['stdout'] | from_json)['rojo']  }} {{ '

        ' -}} ledsAzul: {{ (rgbic['stdout'] | from_json)['ledsAzul']  }} {{ '

        ' -}} ledsNaranja: {{ (rgbic['stdout'] | from_json)['ledsNaranja']  }}
        {{ '

        ' -}} ledsRojo: {{ (rgbic['stdout'] | from_json)['ledsRojo']  }} {{ '

        ' -}} stderr: {{ rgbic['stderr'] }} {{ '

        ' -}} 
    enabled: false
  - action: localtuya.set_dp
    metadata: {}
    data:
      device_id: *********
      dp: 61
      value: AAEAFAAAAAAAAAA=
  - action: localtuya.set_dp
    metadata: {}
    data:
      device_id:  *********
      dp: 61
      value: "{{ (rgbic['stdout'] | from_json)['ledsAzul'] }}"
  - if:
      - condition: template
        value_template: "{{ (rgbic['stdout'] | from_json)['azul'] | int(0) > 0 }}"
    then:
      - action: localtuya.set_dp
        metadata: {}
        data:
          value: "{{ (rgbic['stdout'] | from_json)['ledsAzul'] }}"
          device_id:  *********
          dp: 61
  - if:
      - condition: template
        value_template: "{{ (rgbic['stdout'] | from_json)['rojo'] | int(0) > 0 }}"
    then:
      - action: localtuya.set_dp
        metadata: {}
        data:
          value: "{{ (rgbic['stdout'] | from_json)['ledsRojo'] }}"
          device_id:  *********
          dp: 61
  - if:
      - condition: template
        value_template: "{{ (rgbic['stdout'] | from_json)['naranja'] | int(0) > 0 }}"
    then:
      - action: localtuya.set_dp
        metadata: {}
        data:
          value: "{{ (rgbic['stdout'] | from_json)['ledsNaranja'] }}"
          device_id:  *********
          dp: 61
alias: Update solar
description: ""
```


/usr/local/bin/rgbic
`#!/bin/bash

# Función para convertir un string hexadecimal a Base64
hexToBase64() {
    local hexString=$1
    local result

    # Eliminar espacios en el string hexadecimal
    hexString=$(echo $hexString | tr -d ' ')

    # Comprobar si la longitud del string es par
    if [ $((${#hexString} % 2)) -ne 0 ]; then
        result="Longitud incorrecta (debe ser par)"
    else
        # Convertir el string hexadecimal a binario y luego a Base64
        result=$(echo "$hexString" | xxd -r -p | base64)
    fi

    echo "$result"
}
# Función para convertir de decimal a hexadecimal con longitud mínima
convertDecToHex() {
    local decimal=$1
    local length=$2
    local hex=$(printf "%0${length}X" "$decimal")  # Convertir a hexadecimal y asegurar longitud
    echo "$hex"
}

# Función para formatear el hexadecimal
numHex() {
    local s=$1
    local hex=$(convertDecToHex $s 2)  # Convertir el número decimal a hexadecimal con longitud de 4
    # Extraer los primeros 2 caracteres y luego los siguientes 2
    echo "$hex"
}





production=$1
consumption=$2
#testing purposes
#consumption=4000
# Convertir los valores flotantes a enteros (sin redondear)
production=$(echo "$production" | awk '{print int($1)}')  # Truncar decimal
consumption=$(echo "$consumption" | awk '{print int($1)}')  # Truncar decimal

maxPower=5000
maxSegments=20

# Calcula el número total de LEDs que se encienden por la producción
ledsGenerados=$(( (production * maxSegments + maxPower - 1) / maxPower ))

# Calcula cuántos LEDs se deben colorear en azul, en función del consumo
ledsConsumidos=$(( (consumption * maxSegments + maxPower - 1) / maxPower ))

# Si el consumo excede o es igual a la producción, se colorean todos los LEDs en azul
if [ "$consumption" -ge "$production" ]; then
  #ledsAzul=$(( (consumption * maxSegments + maxPower - 1) / maxPower )) # No exceder la producción
  ledsRojo=$(( (consumption * maxSegments + maxPower - 1) / maxPower ))
  ledsAzul=0
  ledsNaranja=$ledsGenerados
else
  # Los LEDs azules son todos los generados
  ledsAzul=$ledsGenerados
  # Los LEDs naranjas son el excedente (de la producción) después de consumir
  ledsNaranja=$((ledsGenerados - ledsConsumidos))
  ledsRojo=0
fi
rojo=$ledsRojo
azul=$ledsAzul
naranja=$ledsNaranja
# Imprime el resultado
#echo -e -n "Azul: $ledsAzul LEDs\nNaranja: $ledsNaranja LEDs\n"
ledsRojo=$(numHex $ledsRojo)
ledsAzul=$(numHex $ledsAzul)
ledsNaranja=$(numHex $ledsNaranja)
#echo -e -n "Azul: $ledsAzul LEDs\nNaranja: $ledsNaranja LEDs\n"


ledsAzul="00 02 00 14 01 00 d9 03 e8 03 e8 00 $ledsAzul"
ledsNaranja="00 02 00 14 01 00 19 03 e8 03 e8 00 $ledsNaranja"
ledsRojo="00 02 00 14 01 00 01 03 e8 03 e8 00 $ledsRojo"
#AAIAFAEA2QPoA+iBCA==echo -e -n "$ledsAzul \n"
#echo -e -n "$ledsNaranja \n"


ledsAzul=$(hexToBase64 "$ledsAzul")
ledsNaranja=$(hexToBase64 "$ledsNaranja")
ledsRojo=$(hexToBase64 "$ledsRojo")
#echo "AAEAFAAAAAAAAAA="
#echo -e -n "$ledsAzul \n"
#if [ "$production" -gt "$consumption" ]; then
#  echo -e -n "$ledsNaranja \n"
#fi

#json_output="{\"azul\": \"${ledsAzul}\", \"naranja\": \"${ledsNaranja}\"}"
#echo "$json_output"
#echo "{\"azul\": \"$azul\", \"naranja\": \"$naranja\,\"ledsAzul\": \"$ledsAzul\", \"ledsNaranja\": \"$ledsNaranja\"}"
#echo "{\"azul\": \"$azul\", \"naranja\": \"$naranja\", \"ledsAzul\": \"$ledsAzul\", \"ledsNaranja\": \"$ledsNaranja\"}"
#echo "{\"azul\": \"$azul\", \"naranja\": \"$naranja\", \"ledsAzul\": \"$ledsAzul\", \"ledsNaranja\": \"$ledsNaranja\", \"consumo\": \"$consumption\", \"produccion\": \"$production\",\"rojo\": \"$rojo\", \"ledsRojo\": \"$ledsRojo\"}"
echo "{\"consumo\": \"$consumption\", \"produccion\": \"$production\", \"azul\": \"$azul\", \"naranja\": \"$naranja\", \"rojo\": \"$rojo\", \"ledsAzul\": \"$ledsAzul\", \"ledsNaranja\": \"$ledsNaranja\",  \"ledsRojo\": \"$ledsRojo\"}"
`
