### ISSUE TITLE
loss of connection to tuya devices

### ISSUE THREAD

**Issue by jfparis** [rospogrigio/localtuya#140]
My setup

I have 3 tuya plugs on the network all operated through tuyalocal
```
- host: 192.168.0.28
  local_key: redacte]
  device_id: bf50b24b0a08e11cafgxev
  friendly_name: tuya_sofa_light
  protocol_version: "3.3"
  entities:
  - platform: switch
    friendly_name: sofa_light
    id: 1
- host: 192.168.0.29
  local_key: redacted
  device_id: bf7467d4e337282b8dx3eg
  friendly_name: tuya_office_light
  protocol_version: "3.3"
  entities:
  - platform: switch
    friendly_name: office_light
    id: 1
- host: 192.168.0.43
  local_key: redacted
  device_id: 6000521070039fceaa7a
  friendly_name: tuya_laptop_plug
  protocol_version: "3.3"
  entities:
  - platform: switch
    friendly_name: laptop_plug
    id: 1
    current: 18 
    current_consumption: 19 
    voltage: 20 
```
Issue: After a while, some devies become unreachable through home assistant. There does not seems to be a precise time pattern
This happened several times during the log I am uploading
* at 2020-11-04 23:44:14 I tried to turn off the switch tuya_sofa_light/bf50b24b0a08e11cafgxev in hass and the device did not respond. It turn out that the connection had dropped and not reconnected earlier at 2020-11-04 23:07:40 
* at 2020-11-04 23:44:20 same issue with tuya_laptop_plug 6000521070039fceaa7a. It turned out that the connection had dropped at 2020-11-04 20:27:39
* at 2020-11-05 08:01:21 tuya_sofa_light/bf50b24b0a08e11cafgxev  is out again, having dropped at 2020-11-05 06:56:05

During the first 2 occurence, the wifi was busy as I was streaming something on the TV which is connected onto the same wifi router
Last drop was over night with pretty much nothing happening

The last debug message seems to be `Wait was aborted for seqno 1` after which the reconnection loop fails. 

I am running the latest version from the master with a few modification to make the logging more verboe and useful (tagging the device)

When a connection is lost, I can recover by restarting the localtuya integration

Lastly I am pretty confident there is no application trying to access them other than HASS as I have uninstalled smartlife from my android phone

**Comment by jfparis** [comment]
[tuya-error-log2.log](https://github.com/rospogrigio/localtuya/files/5493091/tuya-error-log2.log)
Log file attached. It's large but hopefully, the timestamp provided above will help

**Comment by pergolafabio** [comment]
i have some RGB led strips
i HA log, i see every 5 min a disconnected message, when the connection is failed
its not reconnecting automaticly, while IP is still the same
i can still ping the led strip ... i have to restart HA to make in functional again

is this the same issue?

**Comment by jfparis** [comment]
Having spent some time going through the logs this is what I think is happening
* The wifi connection drops for reasons that are unclear to me. 
* localtuya/pytyua try to reconnect. Most of the time it works fine 
  - although the logbook of homeassistant is filled with status unknown (which would be nice to be avoided)
* in some cases this fails. This has to do with the async code and I am slihtly out of depth here
  - there seems to be some multiple reentry in the connection loop
  - the code tries to address this but there seems to be a race condition that leeds to no reconnection attempt being made

**Comment by postlund** [comment]
@pergolafabio Can you re-run and try to reproduce using version from `master` and publish the logs here? I would like to see what is happening with the re-connect logic and why it's failing. Same question to you @jfparis, but we are probably covered in #136 already.

**Comment by pergolafabio** [comment]
yeah, i am running master now, but i didnt have the issue anymore now, i updated master already evertime a commit was changed

**Comment by postlund** [comment]
Ok, cool. Let it run for a while, maybe it happens later. Also let's here how it goes for @jfparis.

**Comment by jfparis** [comment]
I reinstalled this morning. I will run it for a few days and report at the weekend (keep this open)

**Comment by Icescreamlol** [comment]
I occasionally seem to loose connection to my smart plugs as well.
![image](https://user-images.githubusercontent.com/44647640/101137114-9a3c0980-360e-11eb-8aec-fb31fb6c38c2.png)

I hope the following log might help in debugging the problem.
[Log.txt](https://github.com/rospogrigio/localtuya/files/5641251/Log.txt)

**Comment by AlexanderFadeev** [comment]
I am having same issues with lightbulbs. It is very annoying. So I wrote an automation to reload the integration every minute.

```
alias: 'Reload Local Tuya'
description: ''
trigger:
  - platform: time_pattern
    minutes: /1
condition: []
action:
  - service: localtuya.reload
    data: {}
mode: single
```
