### ISSUE TITLE
Integrate Standard Function Set

### ISSUE THREAD

**Issue by Morpheus2018** [rospogrigio/localtuya#149]
Hello everybody,
my socket strip [acme SH3305 Smart](https://www.amazon.de/SH3305-Steckdosenleiste-Mehrfachsteckdose-%C3%9Cberspannungsschutz-Fernbedienung/dp/B07Z545TDF/ref=sr_1_11?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=wlan%2Bsteckdosenleiste&qid=1605028218&sr=8-11&th=1) is divided into 3 groups which can be controlled separately. How do I integrate the Standard Function Set? Currently I can only control the entire power strip.
![Standard Function Set](https://user-images.githubusercontent.com/37088587/98711184-f94a8d80-2384-11eb-8e1e-79787abb7432.png)
Is it configured in /config/configuration.yaml?
How should it look right?
Many thanks.

**Comment by postlund** [comment]
You add three separate switches using ID 1, 2 and 3 respectively. Works with either YAML or via config flow (Integrations). We currently don't support timers, so nothing to do with those (we kinda assume people solve that with automations in Home Assistant instead).

**Comment by Morpheus2018** [comment]
> You add three separate switches using ID 1, 2 and 3 respectively. Works with either YAML or via config flow (Integrations). We currently don't support timers, so nothing to do with those (we kinda assume people solve that with automations in Home Assistant instead).

Thank you very much, I have now understood with the "ID"
But which values for current, current_consumption and voltage are correct? Always for "ID 1" also the value 1 and for "ID 2" the value 2 etc.? I don't understand yet.
```
localtuya:
   - host: 192.168.1.19
    device_id: 16158----------------
    local_key: e5277a--------------
    friendly_name: P-Steckdose
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: Uhr
        id: 1
        current: 1
        current_consumption: 1
        voltage: 1
      - platform: switch
        friendly_name: TV
        id: 2
        current: 2
        current_consumption: 2
        voltage: 2
      - platform: switch
        friendly_name: USB
        id: 7
        current: 7
        current_consumption: 7
        voltage: 7
```
