### ISSUE TITLE
Unable to add power consumption to HA assistance 

### ISSUE THREAD

**Issue by dekela** [rospogrigio/localtuya#1527]
Although Current,Voltage and Current_Consumption is being displayed in the attributes and I created sensors following the readme guide enteties are not dispplayed in the energy dashboard to be added to individual power consumpption.

Based on:
https://www.home-assistant.io/more-info/statistics/

This is a problem with the integration not providing long term statistics:
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

Can it be done? Am I doing something wrong?

Thanks
Dekel

**Comment by PaulCavill** [comment]
Hey this is my setup that works with the energy dashboard

This is the raw switch
![image](https://github.com/rospogrigio/localtuya/assets/108971756/7ccc9611-8e72-4140-9327-8e5b54c930a6)

sensor.yaml
`
- platform: template
  sensors:
    arlec_2_consumption:
      unique_id: "arlec_2_consumption"
      friendly_name: "Arlec 2 Consumption"
      unit_of_measurement: "W"
      value_template: '{{ state_attr("switch.arlec_2", "current_consumption") | float(0) }}'
      device_class: power

- platform: integration
  unique_id: arlec_2_consum_kWh
  source: sensor.arlec_2_consumption
  name: arlec 2 consumption kWh
  unit_prefix: k
  round: 2
  method: left
`
then I have this added to the dashboard.

![image](https://github.com/rospogrigio/localtuya/assets/108971756/d2a43d92-1d6e-47fc-99c0-970fb57b9f85)

![image](https://github.com/rospogrigio/localtuya/assets/108971756/6fe00c25-918a-42e6-a424-3a6d0e7641c8)

**Comment by zillion42** [comment]
@dekela 
I have the same problem.

@PaulCavill 
I already have Rieman Integration and it works for energy, but I would like to record statistics on the Power Consumption and display them in the statistics graph card. I tried all kinds of template sensors, but they won't work.
Is there any chance get this done?

**Comment by zillion42** [comment]
I think I found a solutuion... You need to use the new template format and add a state_class

configuration.yaml:

```
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# Localtuya power statistic template sensor in the new template format     
template:
  - sensor:
      - name: "chika_computer_consumption"
        unique_id: "Switch Chika Computer Consumption"
        unit_of_measurement: "W"
        state: "{{ state_attr('switch.chika_computer', 'current_consumption') | float(0) }}"
        device_class: power
        state_class: measurement
  - sensor:
      - name: "fridge_kitchen_consumption"
        unique_id: "Switch Fridge Kitchen Consumption"
        unit_of_measurement: "W"
        state: "{{ state_attr('switch.fridge_kitchen', 'current_consumption') | float(0) }}"
        device_class: power
        state_class: measurement
  - sensor:
      - name: "laundry_dryer_consumption"
        unique_id: "Switch Laundry Dryer Consumption"
        unit_of_measurement: "W"
        state: "{{ state_attr('switch.laundry_dryer', 'current_consumption') | float(0) }}"
        device_class: power
        state_class: measurement
  - sensor:
      - name: "plants_consumption"
        unique_id: "Switch Plants Consumption"
        unit_of_measurement: "W"
        state: "{{ state_attr('switch.plants', 'current_consumption') | float(0) }}"
        device_class: power
        state_class: measurement
  - sensor:
      - name: "yoshi_computer_consumption"
        unique_id: "Switch Yoshi Computer Consumption"
        unit_of_measurement: "W"
        state: "{{ state_attr('switch.yoshi_computer', 'current_consumption') | float(0) }}"
        device_class: power
        state_class: measurement
```
