### ISSUE TITLE
Bug since HA 2023.12 - Tuya climate thermostat no longer working (eurom heater)

### ISSUE THREAD

**Issue by kkoenen** [rospogrigio/localtuya#1596]
## The problem

2023.11.x works fine; thermostats show current temp and can be used to set the three eurom heaters. I have several other thermostats, they are on the warmup platform.

In configuration.yaml:

```
climate:
  - platform: warmup
    username: xxxxxx@xxxxxxx.nl
    password: !secret password_01
  - platform: generic_thermostat
    name: Heater
    heater: switch.heater_power
    target_sensor: sensor.heater_tuyasns_temperature
    min_temp: 12
    max_temp: 24
    target_temp: 19
    initial_hvac_mode: "off"
    precision: 1.0
```
![Selection_3397](https://github.com/rospogrigio/localtuya/assets/1116248/da92115d-0e22-4d95-a4fc-49425ff238aa)

Localtuya, installed via HACS, provides 3 panel heaters (eurom).

After update 2023.12 (and revisions 1,2 and 3 after that), the thermostats look like this:
![Selection_3398](https://github.com/rospogrigio/localtuya/assets/1116248/f313f473-b9b3-47ca-9b84-41ef47aa3a28)

## Environment

- Localtuya version: 5.2.1 
- Home Assistant Core version: 2023.12 
- [X] Does the device work using the Home Assistant Tuya Cloud component ? 
- [?] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [X] Device worked with earlier version of HA.
- [] Are you using the Tuya/SmartLife App in parallel ?
