### ISSUE TITLE
Cannot set temperature or brightness of light

### ISSUE THREAD

**Issue by Rjaap** [rospogrigio/localtuya#161]
I installed two lights via config flow, however I can only set a fraction of the original temperature or brightness range. When I use the smart life app they work fine. Tried different options in config flow, but to no avail.

**Comment by postlund** [comment]
You need to install the version from `master` to get all the settings needed to fix that.

**Comment by ultratoto14** [comment]
If you use master version , maybe the brightness max value is not set correctly.
Can you update your device and set the max brightness slider to 255 ?
A tip to find the right value: If your DP ids are < 20 then choose 255 as max brightness, if its >=20 then 1000

**Comment by Rjaap** [comment]
My DP's are > 20 so I set to a 1000. Will try 255. Currently trying to find out the correct dp's for color and color temperature. Any ideas what those might be?

**Comment by ultratoto14** [comment]
You can check [here](https://github.com/rospogrigio/localtuya/pull/125#issuecomment-719964475)

**Comment by ultratoto14** [comment]
You also have yaml documentation :
```yaml
      - platform: light
        friendly_name: Device Light
        id: 4 # Usually 1 or 20
        color_mode: 21 # Optional, usually 2 or 21, default: "none"
        brightness: 22 # Optional, usually 3 or 22, default: "none"
        color_temp: 23 # Optional, usually 4 or 23, default: "none"
        color: 24 # Optional, usually 5 (RGB_HSV) or 24(HSV), default: "none"
        brightness_lower: 29 # Optional, usually 0 or 29, default: 29
        # for brightness_upper from our current knowledge, 
        # bulb using id (1-5) should be set to 255, bulb using id (20-24) should be set to 1000. 
        brightness_upper: 1000 # Optional, usually 255 or 1000, default: 1000
        color_temp_min_kelvin: 2700 # Optional, default: 2700
        color_temp_max_kelvin: 6500 # Optional, default: 6500
```
