### ISSUE TITLE
Energy consumption cannot be added to the energy UI

### ISSUE THREAD

**Issue by songwei2088w** [rospogrigio/localtuya#1739]
Unable to add the entity type name status_class, so it cannot be added to energy

**Comment by eskalator** [comment]
As i recall it is state_class property of the sensor entity that is lacking and that energy card uses/demands. 

I've tinkered a little  in the sensor.py namely adding state_class property

`@property
    def state_class(self):
        """Return the state class of this device."""
        return self._config.get(CONF_STATE_CLASS)`

and modyfying flow schema to accomodate this 

`def flow_schema(dps):
    """Return schema used in config flow."""
    return {
        vol.Optional(CONF_UNIT_OF_MEASUREMENT): str,
        vol.Optional(CONF_DEVICE_CLASS): vol.In(DEVICE_CLASSES),
        #vol.Optional(CONF_STATE_CLASS): vol.In(STATE_CLASSES),
        vol.Optional(CONF_SCALING): vol.All(
            vol.Coerce(float), vol.Range(min=-1000000.0, max=1000000.0)
        ),
    }`

The result is that i get bullet list to choose state class of the sensor during entity configuration, but it is not saved in resulting entity. 
As i have no experience in python(only common logic/observation-based copy paste *^^*) i cannot continue this as it goes way beyond my skills. 
It seems like an easy thing to do for the author/maintainer who has the knowledge of the whole integration structure and used functions and it is very quality-of-life valuable feature.

**Comment by npa-homeassistant** [comment]
I have had the same problem. If I've understood what you're saying, you can fix this in your configuration.yaml by adding some customize entries for the errant sensors. For example, I have:

```
  # Customise entities
  customize:

    sensor.mg4_energy:
      device_class: energy
      state_class: total_increasing

    sensor.creator_pro_energy:
      device_class: energy
      state_class: total_increasing

    sensor.island_bread_maker_energy:
      device_class: energy
      state_class: total_increasing

    sensor.air_fryer_energy:
      device_class: energy
      state_class: total_increasing      

    sensor.utility_freezer_energy:
      device_class: energy
      state_class: total_increasing 
      
    sensor.dishwasher_energy:
      device_class: energy
      state_class: total_increasing
```
