### ISSUE TITLE
Question about covers

### ISSUE THREAD

**Issue by darth-aragoth** [rospogrigio/localtuya#187]
Hi,
in 'old' behavior of fake positioning in covers, position was 'stuck' at 50 and when I wanted to open cover by 10, I had to set 55.

Now it's much easier to set desired position, but is there any way to achieve old functionality of raise/lower cover by x%? I tried to modify my old scene (from `current_position: 55`), but whatever I try, I get 'expected int for dictionary value' error...

```
- id: ...
  name: Raise covers by  10%
    cover.east_cover:
      current_position: "{{ state_attr('cover.east_cover', 'current_position') | int }}"
      friendly_name: Cover - east
      supported_features: 15
      state: opening
```
