### ISSUE TITLE
Gu10 Bulb RGBC

### ISSUE THREAD

**Issue by DavidFFerreira** [rospogrigio/localtuya#209]
Hi, i have a hard time to figureit out how I can configure via Flow my bulb

In all SelectBox I have 9 choises that dont makes sense for me (see picture bellow)
Ive tried several combinations without success I always have the same errors
Can you please help me?

Pictures:
https://media.discordapp.net/attachments/534478791159054346/783713246598135859/unknown.png
https://media.discordapp.net/attachments/534478791159054346/783713097600466974/unknown.png?width=274&height=608

Errors:
Exception in _update_handler when dispatching 'localtuya_738165018caab5ef5fac': ({'1': False, '2': 'colour', '3': 133, '5': 'ffffff000000ff', '6': '00ff0000000000', '7': 'ffff500100ff00', '8': 'colour', '9': 'colour', '10': 'colour'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 245, in _update_handler self.status_updated() File "/config/custom_components/localtuya/light.py", line 382, in status_updated hue, sat, value = [ File "/config/custom_components/localtuya/light.py", line 383, in <listcomp> int(value, 16) for value in textwrap.wrap(color, 4) ValueError: invalid literal for int() with base 16: 'colo'

-----------------------------------------------------------------------------------------------------------------------------------------

[139757375087232] 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 499, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 536, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 230, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/config/custom_components/localtuya/light.py", line 319, in async_turn_on
    round(self._hs[0]), round(self._hs[1] * 10.0), brightness
TypeError: 'NoneType' object is not subscriptable

**Comment by ultratoto14** [comment]
Hi @DavidFFerreira,
From your snapshot, can you test with this configuration(take care of the brightness max value):
![image](https://user-images.githubusercontent.com/3328573/100909402-f860d380-34cc-11eb-9112-96ba789acfb2.png)

Report if it works.

**Comment by DavidFFerreira** [comment]
Thanks alot, finally works :D. 

How about Scenes? it doenst work?

**Comment by ultratoto14** [comment]
Scene support is basic as we found afterwards that manufacturer use different ones in the oposite of using the same DP ids.
You can use DP id 6 for scene and see if it works for you 

Can you give also the data to fill up the [wiki](https://github.com/rospogrigio/localtuya/wiki/Known-working-and-non-working-devices) ?

You can find firmware data in the tuya app, Product Key is the model in the HA device list, DP ids can be found using options in integration page for devices setup via config flow.

**Comment by DavidFFerreira** [comment]
@ultratoto14 

how to I get White color in RGBC?
How do I control white balance in RGB+CCT?

models that I have .... 32 in total

Jm5pbvaDrH4ZjHoT   | RGB+CCT | 1,0,3
wqhaj7e0ctvqlhg5      | RGB+CCT | 3,3,31
heeU2AWVxpxfqP6D  | RGBC        | 1,0,7
b9mcasugykzgefgs    | RGBC         | 1,0,0

**Comment by ultratoto14** [comment]
Hi @DavidFFerreira did you check the wiki page [Known working devices](https://github.com/rospogrigio/localtuya/wiki/Known-working-and-non-working-devices) ?

This is for yaml configuration but the recommendations also applies to config_flow:
```yaml
      - platform: light
        friendly_name: Device Light
        id: 4 # Usually 1 or 20
        color_mode: 21 # Optional, usually 2 or 21, default: "none"
        brightness: 22 # Optional, usually 3 or 22, default: "none"
        color_temp: 23 # Optional, usually 4 or 23, default: "none"
        color: 24 # Optional, usually 5 (RGB_HSV) or 24 (HSV), default: "none"
        brightness_lower: 29 # Optional, usually 0 or 29, default: 29
        brightness_upper: 1000 # Optional, usually 255 or 1000, default: 1000
        color_temp_min_kelvin: 2700 # Optional, default: 2700
        color_temp_max_kelvin: 6500 # Optional, default: 6500
        scene: 25 # Optional, usually 6 (RGB_HSV) or 25 (HSV), default: "none"
        music_mode: False # Optional, some use internal mic, others, phone mic. Only internal mic is supported, default: "False"
```

for white balance:
```yaml
        color_temp: 23 # Optional, usually 4 or 23, default: "none"
```
If you have time, can you add the name, brand and the DP ids you used to your last message
