### ISSUE TITLE
GU10 RGBC - Set White color?! How?!

### ISSUE THREAD

**Issue by DavidFFerreira** [rospogrigio/localtuya#210]
Hi there, I've been successeful with the integration. But There is a very anoying "bug"?! In Home assistant, by smartlife or by local tuya, I cannot revert my bulb to White after put in some color. In the color circle, i sellect the midle White, and the bulb stays blue cyan. Usually I need to go back to Smartlife app to put in Cold White

Can u help me?

![image](https://user-images.githubusercontent.com/32928749/100913104-3fe56080-34c9-11eb-8bc9-447744ea7831.png)

**Comment by ultratoto14** [comment]
Hi @DavidFFerreira on which version are you running ?

**Comment by DavidFFerreira** [comment]
@ultratoto14  version off what? All my bulbs are updated and none of tham Get white in HA or NodeRed, I was hoppfull that with this addon it works....but dont :S....only the RGB+cct works because they have white ballance
My supervisor+HA are in the last version

**Comment by ultratoto14** [comment]
The version of this custom_component

**Comment by DavidFFerreira** [comment]
3.1.0
The RGBW (RGB+CCT) works because they have white ballance. The RGBC (cold white only) don't have white ballance, in the APP on TAB White, only have turn on or off(it change color to white when I change my tab position for the TAB White in app)
It never works in HA with normal integration or costum m tuya...and also still don't work with this integration. Why? There is no command ou parameter to set it to white?!
Thnaks for your time, cheers

![image](https://user-images.githubusercontent.com/32928749/100991675-300e6080-354b-11eb-95b1-4bf9ffe3fc6d.png)

**Comment by ultratoto14** [comment]
Can you check the master version, it seems that the white point in color picker has been merged one day after 3.1.0.

**Comment by DavidFFerreira** [comment]
@ultratoto14 how I can do that? sorry for my unexperience with  that

**Comment by ultratoto14** [comment]
@DavidFFerreira in HACS, you have the ability to chose the version to install, at the end of the combo, chose master.

**Comment by DavidFFerreira** [comment]
still 3.1.0, it I reinstall I will lose all the integrations?

**Comment by ultratoto14** [comment]
Use reinstall in the integration menu of localtuya in HACS, choose maser,  you should not lose your already set up devices.

**Comment by DavidFFerreira** [comment]
i'm trying now

**Comment by DavidFFerreira** [comment]
ok,, I think this is it.....just a quick question, how about nodered? I need to parse 255,255,255 value r color_name White, how it will work with your integration?

**Comment by ultratoto14** [comment]
@DavidFFerreira about nodered, I do not have any clue, you can check the source code and see if something can help you .

If the behavior of your bulbs is now correct, please close this issue.

**Comment by DavidFFerreira** [comment]
I will, let me test in all bulbs at the end of the day

**Comment by DavidFFerreira** [comment]
@ultratoto14  its working all good. Thanks

**Comment by jasonalsing** [comment]
Hi,
Using 'master' I am now able to set properly the 'white' color of my bulb (Merkury RGBW), however, if I set the bulb to 'white' in a scene in HA, it does not keep. It lets me set it, and save it, but going back into the scene edit it's always back to previous color.

I even try to set the bulb to 'white' before even adding it to a scene, but still doesn't keep once you active an RGB scene and try to re-activate the white scene.

**Comment by ultratoto14** [comment]
@jasonalsing can you paste here the saved scenes, colour and white?

**Comment by jasonalsing** [comment]
Here is the scene, but when the scene actually activates it does not set the color only the brightness is affected...
```
- id: '1607632918304'
  name: Work DND - Idle
  entities:
    light.merkury_1:
      effect_list: []
      brightness: 148
      friendly_name: Merkury_1
      supported_features: 21
      state: 'on'
    light.merkury_2:
      effect_list: []
      brightness: 255
      friendly_name: Merkury_2
      supported_features: 21
      state: 'on'
  icon: mdi:lightbulb

```

**Comment by ultratoto14** [comment]
@jasonalsing will check. Thanks

**Comment by jasonalsing** [comment]
I checked your code and it seems you are keying on hs[0]=0 to set WHITE_MODE and found that if I just edit the scenes.yaml to include the hs values and reload the scenes now the bulb goes white as expected. But I expect if i ever edit the scene in the GUI I'll have to do this edit again.  

```
- id: '1607984700638'
  name: Tuya White - White
  entities:
    light.merkury_1:
      effect_list: []
      brightness: 128
      hs_color:
      - 128
      - 0
      friendly_name: Merkury_1
      supported_features: 21
      state: 'on'
```
