### ISSUE TITLE
Configuring String Lights

### ISSUE THREAD

**Issue by memphisraynz** [rospogrigio/localtuya#211]
I have just purchased a set of strings lights (https://www.bunnings.com.au/arlec-rgb-colour-changing-grid-connect-smart-160-led-ball-lights_p0180228)
I have gone through the process and started trying to set them up in HA.
I am struggling to work out how to set them up, hoping you may be able to point me in the right direction.

Through the Smart Life app they can;
-Change colour
-Change brightness
-Change mode ( single colour, multiple colours, flashing.... 7 modes in total)

I couldn't work out how to do anything other than power on and off.
I performed a DP dump and worked out what the DP's do;
DPS [1] VALUE [False] (Power)
DPS [101] VALUE [1] (Mode 1-7)
DPS [107] VALUE [64] (Brightness 10-64)
DPS [108] VALUE [10] (Doesn't change)

any direction woul be great, thank you

**Comment by ultratoto14** [comment]
Hi @memphisraynz, the behavior of your light is completely different than other lights.
Can you list the different modes available in the tuya app ?
Can you tell me if the Brightness can be changed in all modes ?

**Comment by memphisraynz** [comment]
Thanks,
In the Tuya app I have;
On/Off
Dimmer (brightness)
Transition speed (speed between changing colours in some modes)
Colour picker
Modes 1-7 ( they aren't named just numbers)

Brightness isn't available in all modes. There's one for example, rainbow multi colour that it doesn't affect.
I set brightness to 107 and set the min max to 10-64. When I change it in HA the brightness doesn't change but it reflects exactly in the Tuya app. So if in HA I set it at 50% when I open Tuya it changes to 50%

**Comment by ultratoto14** [comment]
@rospogrigio, @postlund it could be great to give access to set DP via an HA service. This may help users using that as workaround for non standard implementation.
Thoughts ?

**Comment by memphisraynz** [comment]
I don't know if it would be of any help.
I had come across this article of similar lights, it looks like it just doesn't have the colour changing function.

**Comment by ultratoto14** [comment]
The goal is to give you the ability to choose the mode.

**Comment by postlund** [comment]
@ultratoto14 Yes, we should have a set-service of some sort. That was part of my "debug"-PR a while back, but I decided to scrap that and aimed for a set-service instead. Unless you want to give it try to implement, I can try to do it when I have some time. Should be fairly simple.

**Comment by ultratoto14** [comment]
@postlund great, at the moment, i just have time to write messages, no real time to dev, but it's great to ear you.

**Comment by memphisraynz** [comment]
Hi, hopefully not pushing anyone here, appreciate the replies.
In regards to being able to set color, brightness or modes. Do I need to wait until someone has the chance to implement the service calls or is there someone I could try?

Say if I left it in Mode 1, which is just a single colour. Is there I could alter the brightness and colour from HA?
I've played with the values for brightness but changing from HA has no effect, I've altered the values, but it looks like they need to be min10, max 64. if I change to say 0 and 255. Putting the brightness to max in the Tuya app moves the slides to 64 in HA.

I set colour to 107 as well as a test, but HA logs keep asking to set color_mode, ever value i put in there either makes the light unavailable or results in an error of unknown DPS.

If I need to wait or its not possible thats fine.

**Comment by ultratoto14** [comment]
@memphisraynz what is your HA config for the light ?
Can you test with the Tuya app, setting min and max values for brightness and dump the values using  [HOWTO-get-a-DPs-dump](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump)?

**Comment by memphisraynz** [comment]
Hi,
I have already done the DP dump;
DPS [1] VALUE [False] (Power)
DPS [101] VALUE [1] (Mode 1-7)
DPS [107] VALUE [64] (Brightness 10-64)
DPS [108] VALUE [10] (Doesn't change)

- host: 192.168.1.119
  device_id: xxx
  local_key: xxx
  friendly_name: "Kids Lights"
  protocol_version: "3.3"
  entities:
    - platform: light
      friendly_name: Fairy Lights
      id: 1
      brightness: 107
      brightness_lower: 10
      brightness_upper: 64
      #color: 108
      #color_mode: 108

I had been playing with the colour and mode, but disabled with because they throw errors

**Comment by ultratoto14** [comment]
When you put in single color mode,  you can change the color with the tuya app ? What are the changing DP, did you give the full dump ?

We need more data, we think about putting in place a device database to implement different devices like yours but at the moment,  it may not be possible to support yours as it is so different.

**Comment by memphisraynz** [comment]
Hi,
I changed the colour, but none of the DPs changed.
In regards to a ful ldump, I ran ./test.py <deviceID> <IPaddress> <localKey>. Unless there is a switch I could add, the above was the full dump.
I figured that the colour must be a subset of one of the other DPs.

Thanks for your time so far.

**Comment by memphisraynz** [comment]
Out of curisosity I changed;
color: 101
color_mode: 2
101, is the DP that changes when when I change scene/modes. I get the colour wheel in HA, but when I chane the colours they are mixed up. IE, green in blue, blue is red... In your exmaples you say 2 or 21, both result in mixed colours.
Whlie changing colours I run the DP dump and value 101 doesnt change.
Using Scene as 101, looks like it results in incorrect commands being sent to the device. So it might just flash randomly. Whlie it's doing that, when I run the DP dump, the scene DP hasn't changed.

**Comment by memphisraynz** [comment]
Sorry for spamming.
I was playing with https://github.com/sjthespian/addon-tuyagateway
Going through the logs I noticed a new DPS 109, this would change with the colour. example DPS "7gD"
I manually added 109 to the yaml in localtuya but it tells me its an invalid DPS.

**Comment by ultratoto14** [comment]
This integration does not support your kind of device, i know it's frustrating but do not try to change DP ids to whatever, it will not work. What we need is completely picture of the data to understand how it works and then change the necessary code.

For the moment, the supported tuya lights uses:
```yaml
        id: 4 # This is usually true/false value indicating a switch
        color_mode: 21 # this contains the hardcoded values "white","colour","scene" or "music"
        brightness: 22 # this contains a value to control the brightness of the white color, two kind are managed "25-255" and "10-1000"
        color_temp: 23 # this is the white color temp, this uses the same range as brightness
        color: 24 # this is the color value, two kind of encoding supported, 12 char length pure HSV, 14 char length RGB and HSV 
        brightness_lower: 29 # this is setting up the min value for brigthness
        brightness_upper: 1000 # this is setting up the max value for brigthness, and should respect DP 22 range
        color_temp_min_kelvin: 2700 # this values are used to map the min and max mired for the color temp
        color_temp_max_kelvin: 6500 # 
        scene: 25 # this is work in progress, i do not recommend to use them.
```

So your device cannot be mapped, somewhere, you should have a DP with the chosen color stored.

I do not know how you got your device key but if you have tuya-cli, you can try also with it :
```
 tuya-cli get --ip 192.168.1.10 --id bf9421e1849ecc224nfqw --key 2cddf4113ee52a01 -a --protocol-version 3.3
```
Check if you have the same results as with test.py.

**Comment by memphisraynz** [comment]
Hi,
As a coincidence I did run that roday as I came across it, seeing if there were any difference.
the tuya-cli gave me the same results as above.

**Comment by memphisraynz** [comment]
So from what i've manage to establish.

DPS [1] -  Power
DPS [101] - Scene 1-7 as an int
DPS [107] - Brightness min 10, max 64
DPS [108] - Doesn't change
DPS [109] - Isn't addressable, but stores the colour code in 3 char '7gD'

For the scene, is it possible to allow for custom entries?

**Comment by ultratoto14** [comment]
> For the scene, is it possible to allow for custom entries?

Not for the moment, we plan to build a db with known devices data and scenes will be there to enhance the integration, but it will take time.

**Comment by ultratoto14** [comment]
Hello @memphisraynz, @postlund just added a PR with a service to set the dp #236.
You can then set a light like:
```yaml
        id: 1
        brightness: 107
        brightness_lower: 10
        brightness_upper: 64
```
Then, define an input select with the scene numbers or scene names, and add an automation that use the service to set the DPS 101 based on that input select.
As the DPS 109 is not addressable we cannot change it but you may still try with the service.
It's not a common behavior but perhaps this 109 is only visible when the 101 is in a specific scene ?
