### ISSUE TITLE
Strange (and seemingly unsupported) cover behavior (Zemismart Roller Shade Motor)

### ISSUE THREAD

**Issue by gentleseal** [rospogrigio/localtuya#215]
This may be #144 or related.

I have a Zemismart Roller Shade Motor ([https://templates.blakadder.com/zemismart_M515EGB.html](https://templates.blakadder.com/zemismart_M515EGB.html)).
YAML config:
```
- host: ...
  device_id: ...
  local_key: ...
  friendly_name: Bedroom Blinds
  protocol_version: "3.3"
  entities:
    - platform: cover
      friendly_name: Bedroom Blinds
      id: 1
      commands_set: open_close_stop
      positioning_mode: position
      position_inverted: true
      current_position_dp: 2
      set_position_dp: 2
```

Controlling the blind (set position, open, close, stop) works fine.

The issue I am facing is that the state of the blind is reported incorrectly (always opening or closing regardless of real state).

It seems that this blind does not have a DP to report back the actual state if not triggered by the actual remote.

Here are the DPs with it closed:
`{
  devId: '...',
  dps: { '1': 'close', '2': 100, '5': false, '7': 'opening', '10': 0 }
}`
opening:
`{
  devId: '...',
  dps: { '1': 'open', '2': 83, '5': false, '7': 'opening', '10': 0 }
}`
open:
`{
  devId: '...',
  dps: { '1': 'open', '2': 0, '5': false, '7': 'opening', '10': 0 }
}`
closing:
`{
  devId: '...',
  dps: { '1': 'close', '2': 23, '5': false, '7': 'opening', '10': 0 }
}`

As you can see DP 7 is useless (think it only responds to being triggered by the remote for whatever reason).
DP 1 (control DP) which I understand the integration expects to read `stop` when the blind is closed/open is just stuck with the last command unless the `stop` command is set explicitly (via API or remote).

It seems the only way to read the state is to imply it from the position (DP 2).

Please let me know if I'm misunderstanding how the integration works or if I'm doing something wrong.
Thanks.
