### ISSUE TITLE
Help with Feit Outlet

### ISSUE THREAD

**Issue by sminker81** [rospogrigio/localtuya#259]
This is probably a dumb question, but I need help. I have multiple Feit Wifi Outlets. No power usage, just on and off. localtuya has no issues auto finding all my lightbulbs, but not the outlets. Running them locally via Homebridge so I have all the keys and IDs. Trying to convert to HA. I can get them to show and work with the Tuya API integration, but I like local control and blocking china devices from the cloud.

I just need an example configuration.yaml. Tried using the ones on the main page but no luck. The yaml passes the verification, it shows overview page, but not responsive.

**Comment by ultratoto14** [comment]
Perhaps, its linked to the fact that most devices only support one connection at a time. Try to remove them from homebridge, ensure, you are not using the tuya app and retry.
Some also report that blocking them from the cloud may make them unavailable, check the opened issues and comments in closed/open PRs.

**Comment by lishan89uc** [comment]
try this 
```
  - host: xxx.xxx.xxx.xxx
    device_id: xxxxxxxxxxxxxxxxxxxxxx
    local_key: xxxxxxxxxxxxxxxxxxx
    friendly_name: Dryer Plug
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: Dryer Plug
        id: 1
        current: 18
        current_consumption: 19
        voltage: 20
        
      - platform: sensor
        friendly_name: Dryer Current
        id: 18
        device_class: current
        unit_of_measurement: "mA"
```
