### ISSUE TITLE
Current consumption issue

### ISSUE THREAD

**Issue by johanvh83** [rospogrigio/localtuya#322]
I've setup Localtuya and everything works expect the current consumption.

This is my Home Assistant configuration.yaml:

```yaml
localtuya:
  - host: 192.168.100.110
    device_id: bfa834fXXXXXXXXXX72axm
    local_key: 4b0xxxxxxxxxxx862
    friendly_name: Kast
    protocol_version: "3.3"
    entities:
      - platform: binary_sensor
        friendly_name: Kast-binary-sensor
        id: 1
        device_class: power
        state_on: "true" # Optional
        state_off: "false" # Optional
      - platform: switch
        friendly_name: kast-local
        id: 2
        current: 18 # Optional
        current_consumption: 19 # Optional
        voltage: 20 # Optional
      - platform: sensor
        friendly_name: kast-voltage
        id: 20
        scaling: 0.1 # Optional
        device_class: voltage # Optional
        unit_of_measurement: "V" # Optional
      - platform: sensor
        friendly_name: kast-current
        id: 18
        scaling: 0.1 # Optional
        device_class: current # Optional
        unit_of_measurement: "mA" # Optional
      - platform: sensor
        friendly_name: kast-current-consumption
        id: 19
#        scaling: 0.1 # Optional
#        device_class: current_consumption # Optional
#        unit_of_measurement: "W" # Optional
```

If I check the configurations as above, with the 3 last lines as comment, the check passes successfully.
Anyway when I remove the comment signs, to devide the readout by 10 and have W as unit of measurement I got below error:

`
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:420
Integration: Hass.io (documentation, issues)
First occurred: 11:29:07 PM (2 occurrences)
Last logged: 11:40:46 PM
Invalid config for [localtuya]: extra keys not allowed @ data['localtuya'][1]['entities'][4]['scaling']. Got 0.1 extra keys not allowed @ data['localtuya'][1]['entities'][4]['unit_of_measurement']. Got 'W' value must be one of ['battery', 'battery_charging', 'cold', 'connectivity', 'door', 'garage_door', 'gas', 'heat', 'light', 'lock', 'moisture', 'motion', 'moving', 'occupancy', 'opening', 'plug', 'power', 'presence', 'problem', 'safety', 'smoke', 'sound', 'vibration', 'window'] for dictionary value @ data['localtuya'][1]['entities'][4]['device_class']. Got 'current_consumption' value must be one of ['binary_sensor'] for dictionary value @ data['localtuya'][1]['entities'][4]['platform']. Got 'sensor'. (See /config/configuration.yaml, line 26). `

Any idea why the 3 last lines occurs a problem?

Thanks for your reply!
