### ISSUE TITLE
Cannot add switch entity in configuration.yaml

### ISSUE THREAD

**Issue by johandewaardt** [rospogrigio/localtuya#344]
I have an EUROM heater, which I can control when I configure it through the Integration in HA. 

When I add the configuration of the heater in configuration.yaml, I get an error: 
Invalid config for [localtuya]: value must be one of ['binary_sensor'] for dictionary value @ data['localtuya'][0]['entities'][0]['platform']. Got 'switch'. (See /config/configuration.yaml, line 197).

Example:
```
localtuya:
  - host: 192.168.1.124
    device_id: 34465526500291426197
    local_key: 034c9f16092e08d9
    friendly_name: KNT Heater
    protocol_version: "3.3"
    entities: 
      - platform: switch
        friendly_name: KNT Heater Switch
        id: 1
        device_class: power
        state_on: "True" # Optional
        state_off: "False" # Optional
 ```
Any idea's?
