### ISSUE TITLE
Cannot Add RGBW bulbs at all via configuration.yaml and the wizard craps out after the second bulb is added

### ISSUE THREAD

**Issue by tblomega** [rospogrigio/localtuya#345]
So I am very new to HASS and YAML files and I am sure that is at play.

I posted on the home assistant forms a few days ago and I have been trying to brute force thic by virtue of different permutations of any and everything I can think to try but every single permutation of using the configuration.yaml file results in the valid configuration checker saying it is invalid. I have 6 bulbs total to add but I have for testing purposes of late only been working with one bulb.

The following is my most recent attempt to add via the .yaml and the error I get from the checker

```
localtuya:
  - host: 192.168.3.12 
    device_id: 06200480dc4f223af701 
    local_key:  139a25a0e96f9d3b 
    friendly_name: Bedroom Lamp B Top 
    protocol_version: "3.1" 
    entities: 
      - platform: light 
        friendly_name: Device Light 
        id: 1 
        color_mode: 2 
        brightness: 3 
        color_temp: none 
        color: 5 
        brightness_lower: 29 
        brightness_upper: 255 
        color_temp_min_kelvin: 2700 
        color_temp_max_kelvin: 6500 
        scene: 6 
        music_mode: False 


Invalid config for [localtuya]: extra keys not allowed @ data['localtuya'][0]['entities'][0]['brightness']. Got 3 extra keys not allowed @ data['localtuya'][0]['entities'][0]['brightness_lower']. Got 29 extra keys not allowed @ data['localtuya'][0]['entities'][0]['brightness_upper']. Got 255 extra keys not allowed @ data['localtuya'][0]['entities'][0]['color']. Got 5 extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_mode']. Got 2 extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_temp']. Got 'none' extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_temp_max_kelvin']. Got 6500 extra keys not allowed @ data['localtuya'][0]['entities'][0]['color_temp_min_kelvin']. Got 2700 extra keys not allowed @ data['localtuya'][0]['entities'][0]['music_mode']. Got False extra keys not allowed @ data['localtuya'][0]['entities'][0]['scene']. Got 6 value must be one of ['binary_sensor'] for dictionary value @ data['localtuya'][0]['entities'][0]['platform']. Got 'light'. (See /config/configuration.yaml, line 36).
```

The .yaml file is preferable for when I get more bulbs later for easy adding. That said using the wizard will work for one some times 2 bulbs but always after the second bulb, some times after the first when clicking next from the screen asking for secret key and IP address it chugs for a bit and then gives "A Unknown error has occured"

I was using the latest everything but as a test I just installed home assistant 4.20 (latest stable not version 5 version) and local tuya 3.1 just to see if recent versions had anything to do with my issues, that did not help.
