### ISSUE TITLE
Support for Tubble air purifier max

### ISSUE THREAD

**Issue by zarya** [rospogrigio/localtuya#367]
Hi would it be possible to intergrate this a bit better especially the fan speed options.

Currently it works fine with service calls but it would really be nice to just be able to set the values for the fan modes.

Device data:
```
 dps: {
   '1': true, -- On/Off RW
   '2': 28, -- 2.5u ppm RO
   '3': 'sleep', -- Fan mode [sleep,M,H,auto] RW
   '5': 78, -- Filter used RO
   '7': false, -- Child lock RW
   '11': false, -- Filter reset RW
   '18': 'cancel', -- Timer description [cancel,2h,4h,8h] RW
   '19': 0, -- Timer in minutes RO
   '21': 'great', -- Air Quality RO
   '22': 0, -- Fault RO
   '101': 'Standard' -- Light mode [Standard,Soft,Close] RW
 }
```
Basic working hass config
```
    entities:
      - platform: switch
        friendly_name: Purifier
        id: 1
      - platform: sensor
        friendly_name: 2.5 ppm
        unit_of_measurement: ppm
        id: 2
      - platform: sensor
        friendly_name: Mode
        id: 3
      - platform: sensor
        friendly_name: Filter health
        id: 5
        unit_of_measurement: "%"
      - platform: switch
        friendly_name: Purifier Child lock
        id: 7
      - platform: sensor
        friendly_name: Air quality
        id: 21
```
