### ISSUE TITLE
"Extra keys not allowed" after HACS upgrade to 3.2.2

### ISSUE THREAD

**Issue by mrgadget** [rospogrigio/localtuya#388]
First off - thanks for the great addon - great to not have to flash everything!

I had a fan that worked under a previous version (installed around a month ago, sorry I'm now not sure of the previous version number), then after the upgrade I'm presented with the following error in the log:
```
Invalid config for [localtuya]: extra keys not allowed @ data['localtuya'][1]['entities'][0]['fan_speed_control']. Got 3 extra keys not allowed @ data['localtuya'][1]['entities'][0]['fan_speed_high']. Got '5' extra keys not allowed @ data['localtuya'][1]['entities'][0]['fan_speed_low']. Got '1' extra keys not allowed @ data['localtuya'][1]['entities'][0]['fan_speed_medium']. Got '3' value must be one of ['binary_sensor'] for dictionary value @ data['localtuya'][1]['entities'][0]['platform']. Got 'fan'. (See /config/configuration.yaml, line 112).
```

My localtuya yaml is:
```
- host: 1.2.3.4
  device_id: eb62ff380db4c1335dmivo
  local_key: 5b7f2a6a93096f0d
  friendly_name: iot_mbed_fan
  protocol_version: "3.3"
  entities:
    - platform: fan
      friendly_name: iot_mbed_fan_fan
      id: 1
      fan_speed_control: 3
      fan_speed_low: "1"
      fan_speed_medium: "3"
      fan_speed_high: "5" # Added to fan.py manually (added again after update)

    - platform: light
      friendly_name: iot_mbed_fan_light
      id: 9 # Usually 1 or 20
      brightness: 10 # Optional, usually 3 or 22, default: "none"
      color_temp: 11 # Optional, usually 4 or 23, default: "none"
      brightness_lower: 0 # Optional, usually 0 or 29, default: 29
      brightness_upper: 100 # Optional, usually 255 or 1000, default: 1000
      color_temp_min_kelvin: 2700 # Optional, default: 2700
      color_temp_max_kelvin: 6500 # Optional, default: 6500
```
Is it something I have wrong?

Thanks,
Ben.
