### ISSUE TITLE
possible to add Wifi PIR sensor

### ISSUE THREAD

**Issue by Tyrian81** [rospogrigio/localtuya#441]
on wifi using the tuya cloud this thing is slow as F****
Made a custom ping sensor , for when it detects motion it comes online for a brief moment thus pingable
is this integratable in localTuya

{
  "result": {
    "active_time": 1617989013,
    "biz_type": 0,
    "category": "pir",
    "create_time": 1605887410,
    "icon": "smart/icon/ay1536023421083D2Q1d/156402198180ba176223b.jpg",
    "id": "20401777500291cf0366",
    "ip": "xx.xxxxxx",
    "lat": "xx.xxxxxx",
    "local_key": "xx.xxxxxx",
    "lon": "xx.xxxxxx",
    "name": "PIR bijhok",
    "online": true,
    "owner_id": "xxxx",
    "product_id": "wqz93nrdomectyoz",
    "product_name": "Smart PIR sensor",
    "status": [
      {
        "code": "pir",
        "value": "pir"
      },
      {
        "code": "battery_state",
        "value": "middle"
      }

**Comment by iotinkognito** [comment]
What is your code for? A sensor linked to the cloud version Tuya standard component?

**Comment by Kilkenny-82** [comment]
Would be great to have this in LocalTuya indeed, the JSON responds for my PIR is the same. Think the biggest issue is that polling the PIR would drain the battery. Not sure how a push message could be intercepted.

**Comment by tiimsvk** [comment]
Search ip adrese on router and add ping platform in configuration.yaml
and the like motion, the device sends a signal and then beeps again
```
  - platform: ping
    host: "IP adrese"
    count: 1
    scan_interval: 5
    name: ping_tuya_motion_sensor
  - platform: template
    sensors:
      tuya_motion_sensor:
        friendly_name: "Tuya Motion Sensor Alarm"
        value_template: >-
          {{ as_timestamp(states.sensor.date_time.last_changed) - as_timestamp(states.binary_sensor.ping_tuya_motion_sensor.last_changed) < states('input_number.motion_sensor_idle_secs')|int }}
```
