### ISSUE TITLE
Cannot use decimal scaling factor (eg. 0.1) when setting up through UI

### ISSUE THREAD

**Issue by B-Hartley** [rospogrigio/localtuya#609]
## The problem
Cannot use decimal scaling when setting up through UI.

## Environment

- Localtuya version: HACS install 3.2.3 ?
- Last working localtuya version (if known and relevant):  unknown
- Home Assistant Core version: core-2021.11.0b2
- [x] Are you using the Home Assistant Tuya Cloud component ? installed but disabled
- [x] Are you using the Tuya App in parallel ? installed but not using

## Steps to reproduce

1. Add a new integration, when adding a new sensor, attempt to put in scaling factor of 0.1
2. it won't accept this as it seems to be expecting an integer

## Configuration `configuration.yaml` or `config_flow`

Succesfully setup using YAML.
```
localtuya:
  - host: !secret tuya_bar_ip
    device_id: !secret tuya_bar_device_id
    local_key: !secret tuya_bar_local_key
    friendly_name: Tuya Bar
    protocol_version: "3.3"
    entities:
      - platform: sensor
        friendly_name: Tuya Bar Formaldehyde
        id: 2
        scaling: 0.1
        unit_of_measurement: "mg/m3"
      - platform: sensor
        friendly_name: Tuya Bar Temperature
        id: 18
        scaling: 0.1
        device_class: temperature
        unit_of_measurement: "°C" 
      - platform: sensor
        friendly_name: Tuya Bar Humidity
        id: 19
        scaling: 0.1
        device_class: humidity
        unit_of_measurement: "%"
      - platform: sensor
        friendly_name: Tuya Bar VOC
        id: 21
        device_class: volatile_organic_compounds
        unit_of_measurement: "ppm"       
      - platform: sensor
        friendly_name: Tuya Bar CO2
        id: 22
        device_class: carbon_dioxide
        unit_of_measurement: "ppm"

```

## Provide Home Assistant taceback/logs

```txt

```
## Additional information

Checked for previously raised issue, couldn't find one ?
