### ISSUE TITLE
Light Temp (Warm/Cool) is reversed on the device

### ISSUE THREAD

**Issue by lsaadeh** [rospogrigio/localtuya#615]
## The problem

Arlec 130cm White 4 Blade Grid Connect Smart DC Ceiling Fan With Remote DCF4002WHA
Colour temp through the ui is the reverse of what the colour is on the device.
i.e. warm on the ui is cool on the device and cool is warm.

Maybe this is a bug or maybe this is a request for a feature for the ability to reverse the values set to the device for these settings

## Environment

- Localtuya version: HACS Integration version: 1.16.0
- Last working localtuya version (if known and relevant): N/A
- Home Assistant Core version:  core-2021.11.2
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [x] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Change colour on home assistant to warm
2. Colour of fan light is cool

## Configuration `configuration.yaml` or `config_flow`

```yaml
localtuya:
  - host: <host>
    device_id: <device_id>
    local_key: <local_key>
    friendly_name: Office Ceiling Fan
    protocol_version: '3.3'
    entities:
      - platform: light
        friendly_name: Office Light
        brightness: 10
        brightness_lower: 0
        brightness_upper: 100
        color_temp: 11
        color_temp_min_kelvin: 2700
        color_temp_max_kelvin: 6500
        id: 9
      - platform: fan
        friendly_name: Office Fan
        fan_speed_control: 3
        fan_speed_low: '2'
        fan_speed_medium: '3'
        fan_speed_high: '4'
        id: 1
```

## DP dump

    DPS [1] VALUE [True]
    DPS [3] VALUE [3]
    DPS [4] VALUE [forward]
    DPS [9] VALUE [True]
    DPS [10] VALUE [64]
    DPS [11] VALUE [100]
    DPS [102] VALUE [normal]
    DPS [103] VALUE [off]

## Provide Home Assistant taceback/logs

```txt

```
