### ISSUE TITLE
Help Wanted: How to map a pet feeder?

### ISSUE THREAD

**Issue by junalmeida** [rospogrigio/localtuya#632]
I have a pet feeder that is described like below (via ` tinytuya`): 

``` 
Product ID = vglnuveujzyrpku9  [Valid payload]:
    Address = 192.168.100.xx,  Device ID = eb8b7f156xxxxxxxxx,  Local Key = 1c59xxxxxxx,  Version = 3.3
    Status: {'4': 'standby', '9': False, '18': 0, '19': True, '101': 'no', '102': 'full', '103': True, '104': False, '106': 12, '107': 2}
``` 

So what I'd like to do is to call an action on the device, which is...... FEED!  This action accepts a number which means number of portions it should serve to the tray. 

Is this possible? 

Current workaround: Using the online `TUYA` integration, I can create an action which becomes a `scene` in HA, when I click it, it serves.

Not sure which HA platform is most appropriate for that (`scene`  doesn't seem right), and let alone how to map that function to `localtuya`.

**Comment by junalmeida** [comment]
This is what the current workaround looks like: 
Tuya APP: 
![image](https://user-images.githubusercontent.com/991675/142696713-e4b1ccd0-3f9e-462d-a53a-323a349a71d9.png)

Home Assistant: 
![image](https://user-images.githubusercontent.com/991675/142696828-001a5cc0-fdfe-44d8-aa63-7efefa977c64.png)

**Comment by lkisme** [comment]
> I have a pet feeder that is described like below (via ` tinytuya`):
> 
> ```
> Product ID = vglnuveujzyrpku9  [Valid payload]:
>     Address = 192.168.100.xx,  Device ID = eb8b7f156xxxxxxxxx,  Local Key = 1c59xxxxxxx,  Version = 3.3
>     Status: {'4': 'standby', '9': False, '18': 0, '19': True, '101': 'no', '102': 'full', '103': True, '104': False, '106': 12, '107': 2}
> ```
> 
> So what I'd like to do is to call an action on the device, which is...... FEED! This action accepts a number which means number of portions it should serve to the tray.
> 
> Is this possible?
> 
> Current workaround: Using the online `TUYA` integration, I can create an action which becomes a `scene` in HA, when I click it, it serves.
> 
> Not sure which HA platform is most appropriate for that (`scene` doesn't seem right), and let alone how to map that function to `localtuya`.

It's possible, all you have to do is to find the "Feed DP" by clicking the feed button on App using a certain portion number, and then use the python script to find out which DP has bean changed to the number you just used.
Here is mine:

DP    Value                    Action
3       1-12                      Use HA service set the dp value to the number of portions you want to feed.
4       Standby/active    Feeding status
9       True/false             Switch on to factory set
15      1-12                      Number of portions has bean fed realtime( will changed from 0 to the value your set)

**Comment by junalmeida** [comment]
@lkisme Any idea on how to map the "action" itself? What domain this template could be? I suppose no way to be a "sensor" as sensors have no actions.

**Comment by lkisme** [comment]
I'm using a switch representing the "feed" action, ie, switch it on to feed, and it takes the "feeding status"( DP 4, as a binary sensor) as the state, so it would be switched on when the DP value got set successfully, and switched off when the feeding action is done.
Here is my setting:
```
- platform: template
    switches:
      pet_feeder:
        friendly_name : "Feeder"
        unique_id: switch.wifi.pet_feeder
        turn_on:
          service: localtuya.set_dp
          data:
            device_id: xxxxxx
            dp: 3
            value: >-
                {% set units = states('input_number.portions') | int %} 
                {{units}}
        value_template: >-
            {{states('binary_sensor.feeding_state')}}
        availability_template: >-
            {{states('binary_sensor.feeding_state') != 'unavailable'}}
        turn_off:
```

If you meant to link these sensors and switch to a "device" in HA, you can read here: https://developers.home-assistant.io/docs/device_registry_index/

**Comment by junalmeida** [comment]
interesting, thank you I will try to apply your idea :)

**Comment by junalmeida** [comment]
Thank you @lkisme it is working... For posterity, this is how I end up configuring it: 
```
localtuya:
- host: 192.168.100.42
  device_id: xxxxx
  local_key: xxxxxx
  friendly_name: Pet Feeder
  protocol_version: "3.3"
  entities:
    - platform: sensor
      friendly_name: Pet Feeder State
      id: 4
    - platform: sensor
      friendly_name: Pet Feeder Portions
      id: 106
    - platform: sensor
      friendly_name: Pet Feeder Food Reserve
      id: 102
switch:
- platform: template
  switches:
    pet_feeder:
      friendly_name: "Pet Feeder"
      unique_id: switch.pet_feeder
      turn_on:
        service: localtuya.set_dp
        data:
          device_id: xxxxx
          dp: 3
          value: >-
            {% set units = states('sensor.pet_feeder_portions') | int %} 
            {{units}}
      value_template: >-
        {{states('sensor.pet_feeder_state') == 'feeding'}}
      availability_template: >-
        {{states('sensor.pet_feeder_state') != 'unavailable'}}
      turn_off:
```
