### ISSUE TITLE
Question: How to add a multi socket in Yaml?

### ISSUE THREAD

**Issue by pergolafabio** [rospogrigio/localtuya#644]
guys, how can we add a multi socket in yaml?  a device that has 2 sockets?
i tried below, but it doesnt give me 2 entities?

thnx

```
  - host: !secret tuya_switch_1_ip
    device_id: !secret tuya_switch_1_id
    local_key: !secret tuya_switch_1_key
    friendly_name: Tuya Switch1
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: Tuya Switch1_1
        id: 1
        current: 18
        current_consumption: 19
        voltage: 20
      - platform: switch
        friendly_name: Tuya Switch1_2
        id: 1
        current: 18 
        current_consumption: 19 
        voltage: 20 
```
