### ISSUE TITLE
Tuya curtains wifi only

### ISSUE THREAD

**Issue by DKprojektai** [rospogrigio/localtuya#649]
Hello, I can't integrate curtain. Can you please check your code and provide some help? Thank you.

## Configuration `configuration.yaml` or `config_flow`
```
localtuya:
  - host: 192.168.1.225
    device_id: xxx
    local_key: xxxx
    friendly_name: BCM700D WiFi
    protocol_version: "3.3"
    entities:
      - platform: cover
        friendly_name: Darbo uzuolaida
        id: 1
        commands_set: 'fz_zz_stop'
```
