### ISSUE TITLE
entities/scene definition

### ISSUE THREAD

**Issue by ThomasCr** [rospogrigio/localtuya#659]
Hi,

I have tested your addon and I got it finally running with my two Atmosphere LED String Lights.

But the definition for scene cant work with your fixed definition. Every Tuya device seems to have a own definition.
Also the music definition need some more options...

For me, I have the following plugin definition:

```
localtuya:
  - host: 192.168.189.201
    device_id: xxxx
    local_key: xxxx
    friendly_name: "Lichterkette Decke"
    protocol_version: "3.3"
    entities:
      - platform: light
        friendly_name: "Lichterkette Decke"
        id: 20
        color_mode: 21
        scene: 52
        music_mode: true

  - host: 192.168.189.202
    device_id: xxxx
    local_key: xxxx
    friendly_name: Lichterlette Tannenbaum
    protocol_version: "3.3"
    entities:
      - platform: light
        friendly_name: "Lichterkette Tannenbaum"
        id: 20  
        color_mode: 21
        color: 24
        scene: 25
        music_mode: true
```

I found the right values with tinytuya monitor mode. So while I in monitor mode, I change settings in the tuya app to find the right id to setup the device. 

For my device at 192.168.189.201 I get:
Switch it on/off:
```
Received Payload: {'dps': {'20': False}, 't': 1639349479}
Received Payload: {'dps': {'20': True}, 't': 1639349482}
```
Switch the Scenes (it can only switch between Scene and Music)
```
Received Payload: {'dps': {'21': 'scene'}, 't': 1639349570}
Received Payload: {'dps': {'52': 'AAABZDIB'}, 't': 1639349799} <- Dauerlicht / Steady-On
Received Payload: {'dps': {'52': 'AB4JZAAB'}, 't': 1639349576} <- Kombination / Combination
Received Payload: {'dps': {'52': 'ABkFZAAB'}, 't': 1639350159} <- Funkelblitz / Twinkle Flash
Received Payload: {'dps': {'52': 'AAwFZAAB'}, 't': 1639349865} <- Wellen / Waves
Received Payload: {'dps': {'52': 'AAUFZDIB'}, 't': 1639350229} <- Langsames Verblassen / Slow Fade?
Received Payload: {'dps': {'52': 'AB0FZAAB'}, 't': 1639350317} <- Verfolgungsblitz / Chasing Flash
Received Payload: {'dps': {'52': 'AAYFZAAB'}, 't': 1639350377} <- Langsames Glühen / Slow Glow
Received Payload: {'dps': {'52': 'ABYFZAAB'}, 't': 1639350481} <- Sequentiell / Sequential
```
Switch to Music Mode:
```
Received Payload: {'dps': {'21': 'music'}, 't': 1639350604}
Received Payload: {'dps': {'42': '000100000000'}, 't': 1639350610} <- local on
Received Payload: {'dps': {'42': '000000000000'}, 't': 1639350613} <- local off
Received Payload: {'dps': {'21': 'music'}, 'type': 'query', 't': 1639350657} <- app on
```

More is not possible for this device. At the Tuya IOT Platform the Firmware config for this device could look like this:
![grafik](https://user-images.githubusercontent.com/226670/145733527-bc088ada-e09d-4db5-aee8-501c8e147da7.png)

But there are a lot more types a "developer" can choose:

![grafik](https://user-images.githubusercontent.com/226670/145733636-fd5320b2-9ba0-406d-ad0e-ddf1027e1d8c.png)

And this looks to me very simple. The simplest option would be, when we can define the scene with every entity definition.
So we also dont need to care about translations...
something like: 
`scene_def: {'AAABZDIB' => 'Dauerlicht', 'AB4JZAAB' => 'Kombination', ......} (sorry not sure about the YAML syntax)`

But wait, now I will show you the definition for my device at 192.168.189.202:

switch on/off:
```
Received Payload: {'dps': {'20': False}, 't': 1639351576}
Received Payload: {'dps': {'20': True}, 't': 1639351577}
```
switch scene:
```
Received Payload: {'dps': {'21': 'scene'}, 't': 1639351610}
Received Payload: {'dps': {'21': 'scene'}, 'type': 'query', 't': 1639351659} <- when I repeat to push on scene icon
# now i have a lot of options, will try to explain only a few of them, because they will be to mush
Received Payload: {'dps': {'25': '0103e8'}, 't': 1639351831} <- palm mode 1 - 100% brightness
Received Payload: {'dps': {'25': '0101f4'}, 't': 1639351845} <-  palm mode 1 - 50% brightness
Received Payload: {'dps': {'25': '01000a'}, 't': 1639351870} <-  palm mode 1 - 1% brightness

Received Payload: {'dps': {'25': '0503e8'}, 't': 1639351901} <- palm mode 2 - 100% brightness
Received Payload: {'dps': {'25': '0501f2'}, 't': 1639352055} <- palm mode 2 - 50% brightness
Received Payload: {'dps': {'25': '05000a'}, 't': 1639352084} <- palm mode 2 - 1% brightness

Received Payload: {'dps': {'25': '1003e8'}, 't': 1639352239} <- palm mode 3 - only 100% brightness possible
Received Payload: {'dps': {'25': '1103e8'}, 't': 1639352524} <- palm mode 4 - 100% brightness 
Received Payload: {'dps': {'25': '11000a'}, 't': 1639352572} <- palm mode 4 - 1% brightness

Received Payload: {'dps': {'25': '0103e8'}, 't': 1639352639} <- christmas tree mode 1 - 100% brightness
Received Payload: {'dps': {'25': '0101f0'}, 't': 1639352711} <- christmas tree mode 1 - 50% brightness
Received Payload: {'dps': {'25': '01000a'}, 't': 1639352738} <- christmas tree mode 1 - 1% brightness
```
switch to music mode:
```
Received Payload: {'dps': {'101': '16403e8100a800e803e8'}, 't': 1639352852} <- Music Mode Energy - highest sensitivity
Received Payload: {'dps': {'101': '10103e8100a800e803e8'}, 't': 1639352902} <- Music Mode Energy - lowest sensitivity
Received Payload: {'dps': {'101': '26403e8100a800e803e8'}, 't': 1639352969} <- Music Mode Rhythm - highest sensitivity
Received Payload: {'dps': {'101': '20103e8100a800e803e8'}, 't': 1639353011} <- Music Mode Rhythm - lowest sensitivity
Received Payload: {'dps': {'101': '36403e8100a800e803e8'}, 't': 1639353050} <- Music Mode Spectrum - highest sensitivity
Received Payload: {'dps': {'101': '30103e8100a800e803e8'}, 't': 1639353074} <- Music Mode Spectrum - lowest sensitivity
Received Payload: {'dps': {'101': '46403e8100a800e803e8'}, 't': 1639353125} <- Music Mode Rolling - highest sensitivity
Received Payload: {'dps': {'101': '40103e8100a800e803e8'}, 't': 1639353160} <- Music Mode Rolling - lowest sensitivity
```

The dimming/color chooser mode of this device works out of the box :+1: 

For the scene we must split the parts: first 3 chars are the scene, the last 3 chars are the dimming value.
So this can also be defined like the upper one, like this:
```
scene_def: {'010' => 'Mode 1', '050' => 'Mode 2', ......} (sorry not sure about the YAML syntax)
scene_def_split: true
```

Also the music mode.... but there I cant figure out how this can be solved...

It would be nice, if you can have a look at it.

Thanks,
Thomas

**Comment by buschtoens** [comment]
I currently only have one Tuya light-related device: [Star Projector](https://solution.tuya.com/projects/CMamw6tl7mwgzm), though it uses a different control panel than shown on the linked eTuya page.

In my [comment (#297)](https://github.com/rospogrigio/localtuya/issues/297#issuecomment-995222641) I have reverse-engineered the scenes encoding:

```yaml
host: nebula.<redacted>
device_id: <redacted>
local_key: <redacted>
friendly_name: Living Room Nebula
protocol_version: "3.3"
entities:
  # ...

  # Nebula: RGB Projector.
  - platform: light
    friendly_name: Nebula
    id: 103 # on / off
    color_mode:
      21
      # white: if saturation == 0x0000
      # color: if saturation >= 0x0001
      # scene: read scene config from DP `scene: 25`
      # music: apparently not available on this device (no mic)
    color:
      24 # 12 byte HSV
      # hue:        0x0000 - 0x0168  [360]
      # saturation: 0x0000 - 0x03e8 [1000],
      #             all RGB combined (white) - selected hue only
      # value:      0x0000 - 0x03e8 [1000]
    scene:
      25 # 2 bytes + n * 26 bytes
      # First 2 bytes:
      #
      # scene_num: 0x00 - 0x08
      #   0x00: ???
      #   0x01: ???
      #   0x02: ???
      #   0x03: ???
      #   0x04: Scene 1, default name "Sleeping"
      #   0x05: Scene 2, default name "Romantic"
      #   0x06: Scene 3, default name "Party"
      #   0x07: Scene 4, default name "Relaxing"
      #
      # Followed by 1 - 8 groups of 26 bytes each:
      # Each group encodes encodes a keyframe from `scene_units`.
      #
      # Group bytes 0 - 5: keyframe transition behavior
      #  +0, 2 | unit_switch_duration:   x00 - 0x64 [100], seconds
      #  +2, 2 | unit_gradient_duration: x00 - 0x64 [100], seconds
      #  +4, 2 | unit_change_mode:
      #        |   0x00: static
      #        |   0x01: jump
      #        |   0x02: gradient
      #
      # Group bytes 6 - 17: nebula color & brightness, like DP `color: 24`
      #  +6, 4 | hue:         0x0000 - 0x0168  [360]
      # +10, 4 | saturation:  0x0000 - 0x03e8 [1000]
      # +14, 4 | value:       0x0000 - 0x03e8 [1000]
      #
      # Group bytes 18 - 25: unknown
      # +18, 4 | brightness:  0x0000 - 0x03e8 [1000]
      #        |    Functionality unknown. It's NOT `brightness: 22`.
      # +22, 4 | temperature: 0x0000 - 0x03e8 [1000]
      #        |   Functionality unknown.
      #
      # Example: Scene 1, "Sleeping", 2 frames
      #
      # SN  SD GD CM     H    S    V  Brig Temp
      # 04  46 46 02  0078 03e8 03e8  0000 0000
      #     46 46 02  0078 03e8 000a  0000 0000
      #
      # Example: Scene 4, "Relaxing", 6 frames
      #
      # SN  SD GD CM     H    S    V  Brig Temp
      # 07  46 46 02  0000 03e8 03e8  0000 0000
      #     46 46 02  0078 03e8 03e8  0000 0000
      #     46 46 02  00f0 03e8 03e8  0000 0000
      #     46 46 02  003d 03e8 03e8  0000 0000
      #     46 46 02  00ae 03e8 03e8  0000 0000
      #     46 46 02  0113 03e8 03e8  0000 0000
```

As mentioned in the OP, this does not match the hard-coded scenes:

https://github.com/rospogrigio/localtuya/blob/5a28cec51762b0aa6b9c3d12443d07761ab3b91d/custom_components/localtuya/light.py#L158-L170

https://github.com/rospogrigio/localtuya/blob/5a28cec51762b0aa6b9c3d12443d07761ab3b91d/custom_components/localtuya/light.py#L50-L90

**Comment by buschtoens** [comment]
@ThomasCr You could use the `localtuya.set_dp` service to manually set the value for fields that are not properly supported yet.

https://github.com/rospogrigio/localtuya/blob/5a28cec51762b0aa6b9c3d12443d07761ab3b91d/custom_components/localtuya/services.yaml#L4-L15

Here's a PoC based on [my configuration](https://github.com/rospogrigio/localtuya/issues/297#issuecomment-995222641) that adds two buttons to manually 
- set the `color_mode` (DP `21`) to `scene`
- set the `scene` (DP `25`) data to a custom scene that fades between green and cyan

<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/834636/146271501-10755b05-aa36-49d4-8bc1-9d94ae834575.png">
<td>

```yaml
type: entities
entities:
  - type: button
    name: Enable Scene Mode
    tap_action:
      action: call-service
      service: localtuya.set_dp
      service_data:
        device_id: <redacted> # Same as `device_id` in `localtuya` configuration.
        dp: 21 # color_mode
        value: scene
  - type: button
    name: Set Custom Scene Data
    tap_action:
      action: call-service
      service: localtuya.set_dp
      service_data:
        device_id: <redacted> # Same as `device_id` in `localtuya` configuration.
        dp: 25 # scene
        value: 04464602007803e803e80000000046460200ae03e803e800000000
  # ...
```
</table>
