### ISSUE TITLE
PIR Sensor battery_percentage

### ISSUE THREAD

**Issue by cthu1hoo** [rospogrigio/localtuya#672]
I managed to get a Chinese PIR battery sensor going with this config:

```
- host: 172.17.170.9
  device_id: aaa
  local_key: bbb
  friendly_name: ccc
  protocol_version: "3.3"
  entities:
    - platform: sensor
      friendly_name: ccc
      id: 1
```

This seems to have a bit of a delay, but it reports PIR status correctly, as opposed to guessing via device_tracker or ping which people also use for those sensors.

However, I can't figure out how to get its battery percentage.  It reports it to the Tuya app and I can see it on the IoT platform, but I couldn't figure out which DP it should be on, and how to get it. Any help?

This is the IoT API call report for the device:

```
{
  "result": {
    "category": "pir",
    "status": [
      {
        "code": "pir",
        "name": "人体感应状态",
        "type": "Enum",
        "values": "{\"range\":[\"pir\",\"none\"]}"
      },
      {
        "code": "battery_percentage",
        "name": "电池电量",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1640168422617
}
```

I power cycled it, ran a tinytuya monitor script against, but it only ever reports anything going on on DP 1 (either 'pir' or 'none'), nothing about battery percentage ever shows up in the logs.

Not directly related, but my sensors live on a separate restricted VLAN, so I had to forward broadcasts like this:

```
# cat /opt/etc/init.d/S99socat
#!/bin/sh

ENABLED=yes
PROCS=socat
ARGS="UDP4-RECV:6667,broadcast UDP4-SENDTO:172.17.172.1:6667"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
```

Mentioning it here in case this helps someone in a similar situation.

**Comment by alexhk90** [comment]
I think I have a very similar battery powered PIR motion sensor and managed to get the battery percentage working via DPS 4: 
```
localtuya:
  - host: !secret tuya_sensor_host
    device_id: !secret tuya_sensor_deviceid
    local_key: !secret tuya_sensor_localkey
    friendly_name: Tuya Device
    protocol_version: "3.3"
    entities:
      - platform: binary_sensor
        friendly_name: Motion Sensor
        id: 1
        device_class: motion
        state_on: "pir"
        state_off: "none"
      - platform: sensor
        friendly_name: Motion Sensor Battery
        id: 4
        device_class: battery
        unit_of_measurement: "%"
```

For reference, this is the corresponding "Standard Status Set" from Tuya IoT:

Code | Type | Values
-- | -- | --
pir | Enum | {   "range": [     "pir",     "none"   ] }
battery_percentage | Integer | {   "unit": "%",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }

And I found the DPS ID by inspecting the localtuya logs (with the level set to debug) for an extended period (over at least a day): 
```
$ less home-assistant.log | grep dps
...
2022-05-11 12:25:55 DEBUG (MainThread) [custom_components.localtuya.pytuya] [...] Decrypted payload: {"dps":{"1":"pir"}}
2022-05-11 12:26:26 DEBUG (MainThread) [custom_components.localtuya.pytuya] [...] Decrypted payload: {"dps":{"1":"none"}}
2022-05-11 20:26:06 DEBUG (MainThread) [custom_components.localtuya.pytuya] [...] Decrypted payload: {"dps":{"4":26}}
2022-05-11 23:00:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [...] Decrypted payload: {"dps":{"1":"pir"}}
2022-05-11 23:01:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [...] Decrypted payload: {"dps":{"1":"none"}}
...
```

It seems this device only wakes up to send an updated status, and when it does it only sends either the motion state or the battery percentage, not both. This is confirmed by the logs on Tuya IoT, and consistent with TuyaDebug / `test.py` [here](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump) returning nothing unless the motion sensor has just been triggered (and in that case only returning the DPS for the motion sensor state).
