### ISSUE TITLE
YAML config flow seems to not be working any more

### ISSUE THREAD

**Issue by codingcatgirl** [rospogrigio/localtuya#687]
## The problem

Since localtuya doesn't discover my smart plug's DPS on power usage, i tried to configure localtuya using the configuration.yml instead of the config flow instead. However, after doing so and restarting home assistant, the loyaltuya integration doesn't show up in the list of active integrations and no devices or entities that have been set up can be shown in the respective configuration pages either. This happens even if i only configure it as a switch with no power consumption, with precisely the same settings that work through the config flow.

Interestingly, while no devices or entities are added, localtuya doesn't completely ignore the YAML settings. This can be seen when trying to add a localtuya device via the config flow. In the first screen, the list of discovered devices, after the device id, the IP address is no longer shown (as it is with unconfigured devices) but instead the name i configured in the YAML is shown. So, the device seems to be configured internally in localtuya in some way, but not be exposed to home assistant as devices/entities. 

## Environment

- Localtuya version: 3.3.0
- Home Assistant Core version: 2021.12.7
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce
1. Configure a tuya smart plug (or, possibly any device) using the YAML configuration, as shown below.
2. Restart
3. Look at the integrations/devices/entities lists.

## Configuration `configuration.yaml` or `config_flow`

```yaml
localtuya:
  - host: 192.168.178.99
    device_id: (as discovered through the config flow)
    local_key: (as determined through the usual means, the key is confirmed to be working when used in the config flow, the switch can be controlled)
    friendly_name: "abcdefg"
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: "hijklmnop"
        id: 1
```

## Provide Home Assistant taceback/logs
I'd like to set the log level to debug, but the method described in the issue template does not work for me. There seems to be no service named logger.set_level.

**Comment by jeremysherriff** [comment]
Debug should be achieved by adding the following lines to configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.localtuya: debug
```

I haven't checked what the issue template says but this is copied directly from my own config.
