### ISSUE TITLE
Climate - No DP for min/max temperature, cannot raise the target temp

### ISSUE THREAD

**Issue by mikeg1130** [rospogrigio/localtuya#713]
I have a couple Atomi space heaters. These devices don't return a DP for the min or max temperatures. Leaving them blank sets a default of 7 for the min and 35 for the max. However, since I am using *F, these values are way too low. With these defaults, I am unable to the target temperature to a reasonable target, unless I manually update the min/max attributes states in Dev Tools first.

I would suggest either allowing the user to type in values for min/max (rather than forced to select a DP), or make the default values dependent on the Fahrenheit/Celsius selection.

**Comment by sebirdman** [comment]
@mikeg1130 i've added an MR that fixes this above. 

Here's my Atomi (with that MR active)

```
    entities:
      - platform: climate
        friendly_name: Mobile Heater
        id: 1 # dps for on/off state
        target_temperature_dp: 2
        current_temperature_dp: 3
        hvac_mode_set: "True/False"
        min_temp: 60
        max_temp: 86
        temperature_step: 1
        precision: 1
        temperature_unit: "fahrenheit"

      - platform: sensor
        friendly_name: "Auto / High / Low"
        id: 4
      - platform: switch
        friendly_name: "Swing"
        id: 8
      - platform: switch
        friendly_name: "Screen"
        id: 10
      - platform: number
        min_value: 0
        max_value: 4
        friendly_name: "Turn off in hours"
        id: 12


      - platform: sensor
        friendly_name: "Eleven"
        id: 11
      - platform: sensor
        friendly_name: "One Oh Two"
        id: 102
      - platform: sensor
        friendly_name: "One Oh Three"
        id: 103
 ```
