### ISSUE TITLE
Issue when adding new multiple binary sensors

### ISSUE THREAD

**Issue by kafej** [rospogrigio/localtuya#729]
## The problem

From time to time when I try to add new device with few binaries, after I click this is the last one

## Environment

- Localtuya version:  3.4.0
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version:  2021.12.10
- [] Are you using the Home Assistant Tuya Cloud component ?  No
- [] Are you using the Tuya App in parallel ?  Yes

## Steps to reproduce

  1. Delete and device
  2. Add it one more time
  3. Repat 

## Configuration `configuration.yaml` or `config_flow`

```yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
automation: !include automations.yaml

# Text to speech
tts:
  - platform: google_translate

script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:

homeassistant:
  packages:
    pack_1: !include monia.yaml
    pack_2: !include kafej.yaml
      
proximity:
  home_kafejid:
    devices:
      - device_track
    tolerance: 50
    unit_of_measurement: km
  home_moniaid:
    devices:
      - device_tracker.iph
    tolerance: 50
    unit_of_measurement: km
  home_residents:
    devices:
      - device_tracker
      - device_trac
    tolerance: 50
    unit_of_measurement: km

group:
  jadalnia:
    name: jadalnia
    entities:
      - switch.sonoff_1
      - switch.sonoff_1
  monitory:
    name: Monitory
    entities:
      - switch.listwamonitor1
      - switch.listwamonitor2
      - switch.listwamonitor3
  kuchnia:
    name: Kuchnia
    entities:
      - switch.sonoff_1
      - switch.sonof
    
fan:
  - platform: xiaomi_miio_airpurifier
    name: Humidifier2
    host: 1
    token: 
    model: zh
    
  - platform: xiaomi_miio_fan
    name: Xiaomi_wentylator
    host: 192
    token: 80

frontend:
    themes: !include_dir_merge_named themes

recorder:
  db_url: mysql:/
  purge_keep_days: 180
              # Everything is included by default.  
              # Ensure you are keeping only what you need to keep DB small
  include:    # Include everything you graph and will want to see later
    domains:
     - switch
     - light
     - sensor
     - binary_sensor
     - device_tracker
              # Everything is included by default.  
  exclude:    # Eliminate anything that you never graph or refer back to
    domains:
      - automation
      - updater
    entities:
      - sun.sun
      - sensor.time
      - sensor.date_time_iso # Don't record date and time
      - sensor.yr_symbol # Ignore this as well
      - group.weather # Don't save weather
      - sensor.next_launch_countdown
google:
  client_id: 460164024219-p
  client_secret: IRTZ
    
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
  
camera:
  - platform: ffmpeg
    name: camera
    input: rtsp://kaf

sonoff:
  username: 
  password: 
 
wake_on_lan:

webostv:
  host: 192
  name: Duży
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      "mac": "60:
  customize:
    sources:
      - "Mult
      - youtube
      - makotv
      - netflix

media_player:

binary_sensor:
  - platform: ping
    host: google.com
    scan_interval: 120

sensor:
  - platform: template
    sensors:
      kafejid_phone_batt:
        friendly_name: Phone Battery (Kafej)
        device_class: Battery
        unit_of_measurement: '%'
        value_template: "{{ state_attr('device_tracker.jseidl_presence', 'battery_level') }}"
        icon_template: >-
            {% set tenths = state_attr('device_tracker.jseidl_presence', 'battery_level') / 10 %}
            {% set numeral = 10 * tenths|int %}
            mdi:battery{% if is_state('binary_sensor.jseidl_phone_charging', 'on') %}-charging{% endif %}{% if 10 <= numeral < 100 %}-{{ numeral }}{% elif numeral < 10 %}-outline{% endif %} 
                
  - platform: qnap
    host: 19
    monitored_conditions:
      - status
      - cpu_usage
      - memory_percent_used
      - network_tx
      - volume_percentage_used

  - platform: template
    sensors:
      temp:
        friendly_name: "Duzytemp"
        unit_of_measurement: "°C"
        device_class: temperature
        value_template: "{{ state_attr('fan.humidifier2', 'temperature') }}"

  - platform: template
    sensors:
      hum:
        friendly_name: "Duzyhum"
        unit_of_measurement: "%"
        device_class: humidity
        value_template: "{{ state_attr('fan.humidifier2', 'humidity') }}"

  - platform: cryptostate
    resources:
    - compare: bnb-usd
      name: bnb
    - compare: btc-usd
      name: bitcoin
    - compare: eth-usd
      name: ethereum
      
  - platform: command_line
    name: log_file_size
    command: "du -m /config/home-assistant.log | cut -f1"
    unit_of_measurement: 'MB'
    value_template: '{{ value | int - 1 }}'
    
  - platform: sql
    db_url: mysql://root:d
    queries:
      - name: db_file_size
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: MB
    
  - platform: dnsip
  
  - platform: version
    name: Latest Available Version
    beta: false
    image: raspberrypi4
    source: hassio
    
  - platform: version
    name: Installed Version
    source: local
    
  - platform: uptime
  
  # Sensor to track available updates for supervisor & addons
  - platform: command_line
    name: Supervisor updates
    command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"addons":[.data.addons[] | select(.version != .installed)]}'''
    value_template: "{{ value_json.addons | length }}"
    json_attributes:
      - newest_version
      - current_version
      - addons

  # Sensors to track updates to other core components (audio, dns and CLI)
  - platform: command_line
    name: Updater Audio
    command: 'curl http://supervisor/audio/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version}'''
    value_template: "{% if value_json.newest_version != value_json.current_version %}on{% else %}off{% endif %}"
    json_attributes:
      - newest_version
      - current_version

  - platform: command_line
    name: Updater DNS
    command: 'curl http://supervisor/dns/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version}'''
    value_template: "{% if value_json.newest_version != value_json.current_version %}on{% else %}off{% endif %}"
    json_attributes:
      - newest_version
      - current_version

  - platform: command_line
    name: Updater CLI
    command: 'curl http://supervisor/cli/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version}'''
    value_template: "{% if value_json.newest_version != value_json.current_version %}on{% else %}off{% endif %}"
    json_attributes:
      - newest_version
      - current_version

  # Alternate updater sensor for core since binary_sensor.updater is very slow to recognize updates
  - platform: command_line
    name: Updater Core
    command: 'curl http://supervisor/core/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version}'''
    value_template: "{% if value_json.newest_version != value_json.current_version %}on{% else %}off{% endif %}"
    json_attributes:
      - newest_version
      - current_version

  - platform: template
    sensors:

      #=========================================
      #=== Raspberry Pi last boot date and time
      #=========================================
      last_boot_date_time:
        friendly_name: Last Boot
        value_template: >
          {% set date = as_timestamp(states('sensor.last_boot')) | timestamp_custom('%d') %}
          {% set date = '{:01}'.format(date | int) %}
          {% if date in ('1', '21', '31') %}
            {% set date = date ~ 'st' %}
          {% elif date in ('2', '22') %}
            {% set date = date ~ 'nd' %}
          {% elif date in ('3', '23') %}
            {% set date = date ~ 'rd' %}
          {% else %}
            {% set date = date ~ 'th' %}
          {% endif %}

          {{ as_timestamp(states('sensor.last_boot')) | timestamp_custom('%H:%M on %a') }} {{ date }} {{ as_timestamp(states('sensor.last_boot')) | timestamp_custom('%b %Y') }}
    
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_free
        arg: /
      - type: disk_use
        arg: /
      - type: memory_free
      - type: memory_use_percent
      - type: memory_use
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
      - type: packets_in
        arg: eth0
      - type: packets_out
        arg: eth0
      - type: ipv4_address
        arg: eth0
      - type: processor_use
      - type: last_boot
      
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'

## DP dump
<!-- 
  Paste here a DP dump, see https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump
  You can also try to qualify your device using the procedure described https://github.com/rospogrigio/localtuya/wiki/Qualifying-a-device
-->

## Provide Home Assistant taceback/logs
<!--
  Provide traces if they are relevant. If the problem is reproducible, try to set the log level to debug for this component at least:
  In Dev Tools => Services:

  logger.set_level
  custom_components.localtuya: debug

-->
```txt

```
