### ISSUE TITLE
Ventair Skyfan speed setting

### ISSUE THREAD

**Issue by oztourer** [rospogrigio/localtuya#763]
I have Ventair Skyfans with Tuya addon (USB) modules. I have managed to get everything working with localtuya but only by modifying async_set_percentage() in fan.py - at line 155 I cast math.ceil(percentage_to_ranged_value(self._speed_range, percentage)) to an integer instead of a string. The exact code:
```
153                 await self._device.set_dp(
154                     #str(
155                     int(
156                         math.ceil(
157                             percentage_to_ranged_value(self._speed_range, percentage)
158                         )
159                     ),
160                     self._config.get(CONF_FAN_SPEED_CONTROL),
161                 )
```
The cast to int is redundant in Python v3 but I left it in for clarity, as math.ceil() actually returns a float in Python v2.x.

I have no idea if this is a breaking change for other brands of fan, but perhaps this could become configurable in the YAML file for localtuya devices? Here is my localtuya.yaml file as it applies to Skyfans (with integrated downlight):

```
- host: <ip>
  device_id: <device_id>
  local_key: <local_key>
  friendly_name: Skyfan with light
  protocol_version: "3.3"
  entities:
    - platform: light
      friendly_name: Skyfan light
      id: 15
      brightness: 16
      brightness_lower: 1
      brightness_upper: 5
    - platform: fan
      friendly_name: Skyfan
      id: 1
      fan_direction: 8
      fan_direction_forward: forward
      fan_direction_reverse: reverse
      fan_speed_control: 3
      fan_speed_min: 1
      fan_speed_max: 5
```
The relevant lines above relate to fan speed, which in my case must send an integer in the range 1 to 5 to set the speed. Sending '1' to '5' as string is rejected and turns off the fan. Perhaps a new key could be supported such as 'fan_speed_commandclass' with allowed values 'str' or 'int' and defaulting to 'str'? Neater would be to recognise 'fan_speed_min: 1' vs 'fan_speed_min: "1"' but I realise that this would be a breaking change for existing users if a string is the required output.
