### ISSUE TITLE
SMART socket 2

### ISSUE THREAD

**Issue by erwin** [rospogrigio/localtuya#768]
It took me a little while to get what [tuya-cli](https://github.com/TuyaAPI/cli) reports as `SMART socket 2` working with tuya-local.

<img src="https://user-images.githubusercontent.com/11534217/157674796-4d69165b-3e6b-4810-ac34-f4ca8be0060c.png" width=50% height=50%>

In my case, when using [TuyaDebug](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump),
<details>

<summary>
I got the following DPS:
</summary>

```
Device <device_id> at 192.168.1.217 key <local_key> protocol 3.3 dev_type type_0a:
    DPS [1] VALUE [True] 
    DPS [9] VALUE [0] 
    DPS [17] VALUE [21] 
    DPS [18] VALUE [222] 
    DPS [19] VALUE [423] 
    DPS [20] VALUE [2305] 
    DPS [21] VALUE [1] 
    DPS [22] VALUE [613] 
    DPS [23] VALUE [34400] 
    DPS [24] VALUE [19446] 
    DPS [25] VALUE [2150] 
    DPS [26] VALUE [0] 
    DPS [38] VALUE [memory] 
    DPS [39] VALUE [False] 
    DPS [40] VALUE [relay] 
    DPS [41] VALUE [False] 
    DPS [42] VALUE [] 
    DPS [43] VALUE [] 
    DPS [44] VALUE []
```
</details>

If you're unable to connect, it's usually that the IP, Device ID or Local Key isn't right. Sometimes while setting up a device, I've had to reset the Local Key multiple times to get it right. I actually like the method of just using the iot.tuya.com website and the tuya app better than tuya-cli for the `SMART plug 2` because there are some stats stored in the other DPS and accessing directly via the Tuya App will make it easier to verify configuration for those in the future.

Here's the configuration that got my `SMART socket 2` working:

```yaml
- host: 192.168.X.Y
  device_id: '<device id>'
  local_key: '<local_key>'
  friendly_name: <Which_One> SMART socket 2
  protocol_version: "3.3"
  scan_interval: 30
  entities:
    - platform: binary_sensor
      friendly_name: <Which_One> Plug
      id: 1
      device_class: power
      state_on: "true"
      state_off: "false"
    - platform: switch
      friendly_name: <Which_One> Switch
      id: 1
    - platform: sensor
      friendly_name: <Which_One> Current
      unit_of_measurement: "mA"
      id: 18
    - platform: sensor
      friendly_name: <Which_One> Power
      unit_of_measurement: "W"
      scaling: 0.1 
      id: 19
    - platform: sensor
      friendly_name: <Which_One> Voltage
      unit_of_measurement: "V"
      scaling: 0.1
      id: 20
    - platform: sensor   
      friendly_name: <Which_One> Total
      unit_of_measurement: "kWh"
      scaling: 0.001
      id: 21
#   - platform: sensor
#     friendly_name: DP9
#     id: 9
#   - platform: sensor
#     friendly_name: DP22
#     id: 22
#   - platform: sensor
#     friendly_name: DP23
#     id: 23
#   - platform: sensor
#     friendly_name: DP24
#     id: 24
#   - platform: sensor
#     friendly_name: DP25
#     id: 25
#   - platform: sensor
#     friendly_name: DP26
#     id: 26

```

I wrote `<Which One>` here because you want give each of these a unique name... Maybe it's "Living Room TV" or "Office Monitor" or "Coffee Maker"...

DP9, and DP22-26 have values, but I'm not sure of the format. Looking at what's shown in the Tuya App, I think these values may be a running total of electricity usage, but that's just a guess.

# Here's what I've got in the Tuya App:

<img src="https://user-images.githubusercontent.com/11534217/157796487-69d36e17-c99e-473b-87ff-e3feba49137a.png" width=50% height=50%>

# Here's what shows up for me now in Home Assistant with the config above:

<img src="https://user-images.githubusercontent.com/11534217/157796545-61ef76a4-40fe-4cec-a39a-cdf0820e65c8.png" width=50% height=50%>

The rounding of numbers is a little bit different on each value, but for my use this is close enough.

The `Office Display Total` when shown in HA is currently too small a value, `0.15` so I think HA is rounding that down to 0... I'm not sure though. May be that I need to configure DP21 differently.

And as I mentioned before, the totals aren't showing up.

Overall works pretty good though. Already for me it's even more functionality than I was hoping for.
