### ISSUE TITLE
HA 2022.4.1 Unit of Measurement Feature needs native_unit_of_measurement

### ISSUE THREAD

**Issue by RJ-Make** [rospogrigio/localtuya#794]

**Comment by CloCkWeRX** [comment]
https://developers.home-assistant.io/docs/core/entity/sensor/ suggests this is optional, what behaviours are you seeing that suggest it is required?

**Comment by RJ-Make** [comment]
> https://developers.home-assistant.io/docs/core/entity/sensor/ suggests this is optional, what behaviours are you seeing that suggest it is required?

It appears without it you cannot use the new [Unit Of Measurement](https://www.home-assistant.io/blog/2022/04/06/release-20224/#adjusting-unit-of-measurement-for-sensors) feature.

<img width="724" alt="2022-04-10_10-05-27" src="https://user-images.githubusercontent.com/8496835/162623264-d24c5145-f034-472a-8a1f-5224d5c34dc5.png">

My particular use-case would allow me to convert a manual added food thermometer from Celsius to Fahrenheit.

**Comment by lindsaymarkward** [comment]
Hi, I appear to have a similar issue. I can't work out how to get my Inkbird IBBQ-4T to give me degrees celsius using localtuya. As per the forum discussion, it used to work if I set the unit to °F (using the exact ° symbol) and HA would auto-convert to C since that's my general setting: https://community.home-assistant.io/t/cannot-get-tuya-integration-to-work/226356/19
Now, no matter what I set in localtuya, I can't get my temperatures to convert - they always report in Fahrenheit with whatever unit I enter next to the value.
Can this be updated now please?
Thank you!

**Comment by barrymossel** [comment]
> Hi, I appear to have a similar issue. I can't work out how to get my Inkbird IBBQ-4T to give me degrees celsius using localtuya. As per the forum discussion, it used to work if I set the unit to °F (using the exact ° symbol) and HA would auto-convert to C since that's my general setting: https://community.home-assistant.io/t/cannot-get-tuya-integration-to-work/226356/19 Now, no matter what I set in localtuya, I can't get my temperatures to convert - they always report in Fahrenheit with whatever unit I enter next to the value. Can this be updated now please? Thank you!

Same for me. Quite annoying.

**Comment by outrun0506** [comment]
> Hi, I appear to have a similar issue. I can't work out how to get my Inkbird IBBQ-4T to give me degrees celsius using localtuya. As per the forum discussion, it used to work if I set the unit to °F (using the exact ° symbol) and HA would auto-convert to C since that's my general setting: https://community.home-assistant.io/t/cannot-get-tuya-integration-to-work/226356/19
> 
> Now, no matter what I set in localtuya, I can't get my temperatures to convert - they always report in Fahrenheit with whatever unit I enter next to the value.
> 
> Can this be updated now please?
> 
> Thank you!

Hi, same for me

**Comment by barrymossel** [comment]
> > Now, no matter what I set in localtuya, I can't get my temperatures to convert - they always report in Fahrenheit with whatever unit I enter next to the value.
> > Can this be updated now please?
> > Thank you!
> 
> Hi, same for me. Also using a Inkbird IBBQ-4T.
> 
> Just created a Tenplate Sensor to covert for now.

Could you share the sensor please? I don't have any hopes for this repository to be honest, looking at all the open pull requests and issues.

**Comment by outrun0506** [comment]
Will do, currently I'm on vacation. Back home I'll share my Sensor

**Comment by outrun0506** [comment]
@barrymossel 

Here is my Sensor Config for convert °F to °C:

```YAML

- platform: template
  sensors:
    ibbq_sensor1_c:
      friendly_name: "iBBQ Sensor 1"
      unit_of_measurement: '°C'
      value_template: >-
        {{ (((states.sensor.ibbq_sensor1.state | float - 32 )) * 5/9) | round(1) }}
    ibbq_sensor2_c:
      friendly_name: "iBBQ Sensor 2"
      unit_of_measurement: '°C'
      value_template: >-
        {{ (((states.sensor.ibbq_sensor2.state | float - 32 )) * 5/9) | round(1) }}
    ibbq_sensor3_c:
      friendly_name: "iBBQ Sensor 3"
      unit_of_measurement: '°C'
      value_template: >-
        {{ (((states.sensor.ibbq_sensor3.state | float - 32 )) * 5/9) | round(1) }}
    ibbq_garraum_c:
      friendly_name: "iBBQ Garraum"
      unit_of_measurement: '°C'
      value_template: >-
        {{ (((states.sensor.ibbq_sensor4.state | float - 32 )) * 5/9) | round(1) }}

```
