### ISSUE TITLE
After hours fiddling :), can't Get tuna ceiling fan to control any speed...help :) 

### ISSUE THREAD

**Issue by zeltak** [rospogrigio/localtuya#826]
## The problem
Hi all

so as title said I tried configuring a tuya ceiling fan for hours with no success. I have gotten the light and switch to both work but no matter what I tried I cannot get the fan speed to work with Home assistant

This is my current simplified configuration.yaml section anther non of the options worked for me

```

localtuya:
  - host: 192.168.0.194
    device_id: bf9b52c22ef86e461a4o2v
    local_key: f612d1732e20b0e2
    friendly_name: Office fanlight
    protocol_version: "3.3"
    entities:
      - platform: light
        friendly_name: Light
        id: 15
      - platform: switch
        friendly_name: switch
        id: 1
      - platform: fan
        friendly_name: Fan
        id: 3
        fan_speed_control: 3

```

I have tried using `fan_speed_control`, `fan_ordered_list`, `fan_speed_min/max` etc with no success

I have also tried via the flow config and enabling `Fan speed modes list`

nothing seems to work and I always only get an entity with a switch which always beings back the fan speed to `1` no matter what

any help would be super appreciated !

## Environment

- Localtuya version: 3.5.0
- Last working localtuya version NA
- Home Assistant Core version: 
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.1
Kernel version 5.15.41
Agent version 1.2.1
- [] Are you using the Home Assistant Tuya Cloud component ? no
- [] Are you using the Tuya App in parallel ? no
