### ISSUE TITLE
V4 issues and a missing feature

### ISSUE THREAD

**Issue by sambarlick** [rospogrigio/localtuya#881]
## The problem

[config_entry-localtuya-2d9cbe4dbe153b3c6ba126d5d6fe5b2a.json.txt](https://github.com/rospogrigio/localtuya/files/8914866/config_entry-localtuya-2d9cbe4dbe153b3c6ba126d5d6fe5b2a.json.txt)

**Comment by sambarlick** [comment]
## The problem

**Comment by sambarlick** [comment]
Firstly, thanks for v4, the new UI is great and the cloud link is a great idea to pull all the required data from the tuya IoT site and grab the associated device information.

So the missing feature is that once a device is created you cannot add more entities/DPs to it. The only way to do this is to delete the device and create it again with the new entity/DPs. This used to be possible pre v4 to add new entities/DPs to existing devices.

Some bugs I've noticed...

I had to deleted the integration and re-install it and all my devices for them to become useable. Now the Devices keep going offline, and a reboot of HA is required, sometimes two reboots, to bring them back online,

Adding new devices can make the other devices go offline, again rebooting temporarily fixes this.

The LocalTuya button under yaml configuration rebooting "fails the service call" assembly this is because the yaml configuration has been removed.

I've attached the diagnostics, hopefully this helps.
I can add more things if needed.

My router is not an Asus. I have TP Link Deco. I have rebooted it.

**Comment by mkwatchface** [comment]
Hi samarlick,

i have exactly the same problem with devices going offline. In addition to that, i faced a problem pairing an iQ Tech smart plug. I could see the state but i could not control it. Settings were exactly the same as before.

Also, i have a dimmer switch that even before, i could only set up via yaml with the following code:
```
# Local Tuya Yaml  
localtuya:
  - host: -localipaddress-
    device_id: -mydeviceid-
    local_key: -mylocalkey-
    friendly_name: TV Wall Spot Lights
    protocol_version: "3.3"
    entities:
        - platform: light
          friendly_name: TV Wall Spot Lights
          id: 1                      # TV Wall Spot Spot Lights Power ON/OFF
          brightness: 2              # Needed for the dimming bar to appear
          brightness_lower: 5
          brightness_upper: 1000
```

Now that Yaml is gone, when trying to add it under the light domain, i was not able to make it work. There are mandatory fields such as "Color", "Color Temperature" which of course are not supported by the dimmer and even if select "False" for those, the entity remains unavailable. [This is the dimmer](https://www.alza.sk/moes-smart-wifi-touch-dimmer-switch-d6294788.htm)
