### ISSUE TITLE
Documentation: Working Device HT-1522-X Maxcio Aroma Diffiuser

### ISSUE THREAD

**Issue by CDaxi** [rospogrigio/localtuya#886]
Would be nice if we can start a device database with setup instructions here to help each other. 😉

# Device data:
Manifacturer: Maxcio
Model Number: HT-1522-X

# Goals

* Have a proper fan control for both intensity settings
* Have a proper light control which supports the light effects
* The light effect will be switched to static if you turn on the light
* The light effect will be switched to static if you change the color

# Step 1: Entities (only needed changes from default):

## Fan

* Datapoint ID: 1
* Fan Speed Control dps: 103
* minimum fan speed integer: 2
* maximum fan speed integer: 3
* Fan speed modes list (overrides speed min/max): off,small,big

## Light

* Datapoint ID: 11
* Brightness: 111
* Color Temperatur: (empty)
* Brightness Lower Value: 0
* Brightness Upper Value: 255
* Color Mode: 109
* Color: 108

# Select (Light mode)

**Please replace values like `<KEY>` to your needs.**

* Valid entries: 1;2;3
* User Friendly options: <FRIENDLY_LABEL_GRADIENT>;<FRIENDLY_LABEL_FIXED>;<FRIENDLY_LABEL_NIGHTLIGHT>
  * Example English: Gradient;Fixed;Nightlight
  * Example German: Farbwechsel;Statisch;Nachtlicht

# Binary sensor (Fault, no water)

* On Value: 1
* Off Value: 0
* Device Class: problem

# Step 2: Add template entities to configuration.yaml

**Why are template entities necessary?**
Know, we have a fan, light, binary sensor and a select for different color modes.
The fan speed is displayed wrong (33% off, 66% small, 100% big).
If you remove the first value, the diffuser does not turn off correctly.
We will need to add two template entities in configuration.yaml to:
* Fix percentage issue
* Add effects to light (Gradient, Fixed, Nightlight)

## Add proper fan template:

**Please replace values like `<KEY>` to your needs.**

Examples:
* `<TUYA_FAN_ENTITY_ID>`: fan.diffuser

```yaml
fan:
  - platform: template
    fans:
      <YOUR_FAN_TEMPLATE_ENTITY_NAME>:
        friendly_name: "<YOUR_FAN_TEMPLATE_ENTITY_FRIENDLY_NAME>"
        value_template: "{{ states('<TUYA_FAN_ENTITY_ID>') }}"
        percentage_template: "{% if (state_attr('<TUYA_FAN_ENTITY_ID>', 'percentage') < 66) %}0{% elif is_state_attr('<TUYA_FAN_ENTITY_ID>', 'percentage', 66) %}50{% else %}100{% endif %}"
        speed_count: 2
        turn_on:
          - service: fan.turn_on
            target:
              entity_id: <TUYA_FAN_ENTITY_ID>
        turn_off:
          service: fan.turn_off
          target:
            entity_id: <TUYA_FAN_ENTITY_ID>
        set_percentage:
          service: fan.set_percentage
          target:
            entity_id: <TUYA_FAN_ENTITY_ID>
          data:
            percentage: "{{ percentage }}"
```

## Add proper light template:

This entity is only needed if you want to use a light card which supports effects selection.
Mushroom light card does not support effects.
[Light entity card](https://github.com/ljmerza/light-entity-card) for example has support for the effect dropdown selection.

**Please replace values like `<KEY>` to your needs.**

Examples:
* `<TUYA_LIGHT_ENTITY_ID>`: light.diffuser
* `<TUYA_LIGHTMODE_ENTITY_ID>`: select.diffuser_lightmode

```yaml
light:
  - platform: template
    lights:
      <YOUR_LIGHT_TEMPLATE_ENTITY_NAME>:
        friendly_name: "<YOUR_LIGHT_TEMPLATE_ENTITY_FRIENDLY_NAME>"
        value_template: "{{ states('<TUYA_LIGHT_ENTITY_ID>') }}"
        level_template: "{{ state_attr('<TUYA_LIGHT_ENTITY_ID>', 'brightness') }}"
        color_template: "{{ state_attr('<TUYA_LIGHT_ENTITY_ID>', 'hs_color') }}"
        effect_list_template: "{{ ['<FRIENDLY_LABEL_GRADIENT>','<FRIENDLY_LABEL_FIXED>','<FRIENDLY_LABEL_NIGHTLIGHT>'] }}"
        effect_template: "{{ states('select.wc_diffuser_lichtmodus') }}"
        turn_on:
          - service: light.turn_on
            target:
              entity_id: <TUYA_LIGHT_ENTITY_ID>
          - service: select.select_option
            target:
              entity_id: <TUYA_LIGHTMODE_ENTITY_ID>
            data:
              option: "<FRIENDLY_LABEL_FIXED>"
        turn_off:
          service: light.turn_off
          target:
            entity_id: <TUYA_LIGHT_ENTITY_ID>
        set_effect:
          service: select.select_option
          target:
            entity_id: <TUYA_LIGHTMODE_ENTITY_ID>
          data_template:
            option: "{{ effect }}"
        set_level:
          service: light.turn_on
          target:
            entity_id: <TUYA_LIGHT_ENTITY_ID>
          data_template:
            brightness: "{{ brightness }}"
        set_color:
          - service: light.turn_on
            target:
              entity_id: <TUYA_LIGHT_ENTITY_ID>
            data_template:
              hs_color:
                - "{{ hs[0] }}"
                - "{{ hs[1] }}"
          - service: select.select_option
            target:
              entity_id: <TUYA_LIGHTMODE_ENTITY_ID>
            data:
              option: "<FRIENDLY_LABEL_FIXED>"
```

# Step 3: Add Card to Lovelace Dashboard and enjoy your aroma diffuser

** 🏁 Goal reached! **

If your light card does not support effects like Mushroom light card, you can still use the light mode entity to switch between the modes.

# Optional addons:

## Light should be turned off when the diffuser is turned on via lovelace

Add the following service call to turn_on action at the fan template entity:
```yaml
- service: light.turn_off
  target:
    entity_id: <TUYA_LIGHT_ENTITY_ID>
```

## Light should be switched to static mode with specific color when diffuser is turned on via lovelace (example color: blue, brightness 100%)
```yaml
- service: light.turn_on
  target:
    entity_id: <TUYA_LIGHT_ENTITY_ID>
  data:
    hs_color:
      - 240
      - 100
    brightness: 100
- service: select.select_option
  target:
    entity_id: <TUYA_LIGHTMODE_ENTITY_ID>
  data:
    option: "<FRIENDLY_LABEL_FIXED>"
```

I hope you will have fun and these how to helped you to configure the aroma diffuser.

Kind regards from Bavaria, Germany,
Christian (CDaxi) 👋
