### ISSUE TITLE
Update README - yaml code for energy monitoring values

### ISSUE THREAD

**Issue by donburch888** [rospogrigio/localtuya#915]
## The problem
The recommended configuration.yaml code given in README.md for "Energy monitoring values" stopped working for me. 

In trying to get it working I found that 
`states.switch.sw01.attributes.voltage`
should be changed to 
`state_attr('switch.sw01', 'voltage')`

See also the warning under "STATES" in the [HA Templating documentation](https://www.home-assistant.io/docs/configuration/templating/#states)

Sorry I haven't yet done the "how to use github properly" learning curve, hence suggesting this documentation change as a bug report. 

## Environment
- Localtuya version: 4.0.0.0 
- Last working localtuya version (if known a
- Home Assistant Core version: core-2022.6.7 
- Installation Type | Home Assistant OS 8.2
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Configuration `configuration.yaml` 
I suggest the code block under the "Energy monitoring values" section should be replaced with:
```
       sensor:
         - platform: template
           sensors:
             tuya-sw01_voltage:
               value_template: "{{ state_attr('switch.sw01', 'voltage') }}"
               unit_of_measurement: 'V'
             tuya-sw01_current:
               value_template: "{{ state_attr('switch.sw01', 'current') }}"
               unit_of_measurement: 'mA'
             tuya-sw01_current_consumption:
               value_template: "{{ state_attr('switch.sw01', 'current_consumption') }}"
               unit_of_measurement: 'W'
```
